### ISSUE TITLE
Obsolete error message for GenericStorage?

### ISSUE THREAD

**Issue by jokochems** [oemof/oemof-solph#1008]
When I worked on #1007 and looked into the Coveralls output, I detected an Error message for the `GenericStorage` class to be uncovered. It can be found [here](https://github.com/oemof/oemof-solph/blob/fb1c5f79e57cc283ed8a610b7f8f47ffc22c9fc0/src/oemof/solph/components/_generic_storage.py#L273C1-L279C37).

I think it is outdated anyways and instead, we want the Investment object to be passed to `nominal_storage_capacity`. Thus, in my understanding, it could be safely removed. What do you think?

**Comment by p-snft** [comment]
You are right, the warning is unreachable now.
