### ISSUE TITLE
Perhaps wrong argument in examples/storage_investment v1-v3: nominal_value instead of investment

### ISSUE THREAD

**Issue by Siebenfurcht** [oemof/oemof-solph#1014]
In the example (examples/storage_investment) v1-v3 ([here](https://github.com/oemof/oemof-solph/tree/dev/examples/storage_investment)) the argument for generic storage is nominal_value:

`    storage = solph.components.GenericStorage(`
`        label="storage",`
`        inputs={bel: solph.Flow(variable_costs=0.0001)},`
`        outputs={bel: solph.Flow()},`
`        loss_rate=0.00,`
`        initial_storage_level=0,`
`        invest_relation_input_capacity=1 / 6,`
`        invest_relation_output_capacity=1 / 6,`
`        inflow_conversion_factor=1,`
`        outflow_conversion_factor=0.8,`
`        nominal_value=solph.Investment(ep_costs=epc_storage),`
`   )`

This leads to the following error message:
`TypeError: GenericStorage.__init__() got an unexpected keyword argument 'nominal_value''
`
It seems like `nominal_value` should be replaced by `investment`:
`investment=solph.Investment(ep_costs=epc_storage)`

I the documentation it states:

"Investment in this context refers to the value of the variable for the ‘nominal_value’ (installed capacity) in the investment mode." [(here)](https://oemof-solph.readthedocs.io/en/latest/usage.html#genericstorage-component)

I am not that familiar with github yet and perhaps there is something about the version history I am not aware of, thus I wanted to submit it in this form first. Perhaps it was (un)intentionally changed [here](https://github.com/oemof/oemof-solph/commit/63e699ee3a9d244579b2ce1d6e31926ccf32edfb).

Would be great to get some feedback on this issue.

**Comment by jokochems** [comment]
Thank you for opening this issue and I guess you are right about all of it.
I think, `nominal_value` there needs to be replaced with `nominal_storage_capacity` for the `GenericStorage` unit itself, see the [code of the storage component](https://github.com/oemof/oemof-solph/blob/71022830948dac0206560f49615f708a569258ca/src/oemof/solph/components/_generic_storage.py#L202C1-L208C14). It must have been a copy & paste / find & replace error.

**Comment by p-snft** [comment]
Also see #991. (For future releases, I suggest to rename both, `nominal_storage_capacity` and `nominal_value`, to `nominal_capacity`.)
