### ISSUE TITLE
Discounting duplication for fixed costs

### ISSUE THREAD

**Issue by nailend** [oemof/oemof-solph#1019]
There seem to be a duplication of discounting for fixed_costs [here](https://github.com/oemof/oemof-solph/blob/f542a7caf8e73efd03b9297ffda9e9bd326fa04b/src/oemof/solph/flows/_investment_flow_block.py#L1029
)
I will remove the second discounting as its already covered by the list comprehension. Do you agree?@jokochems ?

**Comment by jokochems** [comment]
No, I disagree. It has been introduced intentionally.
* Imagine you invest in year 3 and then have your unit in the system for 10 years.
* Then you first discount the 10 year horizon fixed costs to the start of year 3.
* And then the other discounting is from start of year 3 to 0, i.e. the start of the optimization horizon.

**Comment by jokochems** [comment]
@nailend Do you agree and can we close this issue?

**Comment by jokochems** [comment]
> But the list comprehension is taking care of both as you use:
> 
> ```
>   for pp in range(
>       m.es.periods_years[p],
>       range_limit,
>   )
> ```
> 
> with `m.es.periods_years` being the distance to T=0, isn't it?
> 
> So you directly discount 3,4,5,.... years.

Oh shoot, you are totally right about that. I have been routine-blinded. For me it was clear that the range object starts at 0 which it doesn't. I guess, I had implemented it differently in the first place and must have forgotten to adjust.

Would you provide the (rather small) fix and shall I review then?
