### ISSUE TITLE
Issue with processing and dumping of results in basic example

### ISSUE THREAD

**Issue by ab-bajaj** [oemof/oemof-solph#1027]
While running the basic example with some changes that make the model infeasible, the results were still printed from the dump. 
Attaching a snippet below.

![oemof issue](https://github.com/oemof/oemof-solph/assets/129049853/805de9d7-dd3b-40f1-8acd-760df8e54201)

**Comment by p-snft** [comment]
I agree to both points.

**Comment by p-snft** [comment]
The first of the issues is solved in #1040: The basic example is now (more) basic.
