### ISSUE TITLE
First time step of storage_content sequence is missing

### ISSUE THREAD

**Issue by SabineHaas** [oemof/oemof-solph#1030]
**Describe the bug**
The storage_content sequence of an investment optimization problem is missing the first time step.

Energy system consists of: el_bus, load, el-storage, excess, shortage

**To Reproduce**
[invest_storage.txt](https://github.com/oemof/oemof-solph/files/13512923/invest_storage.txt)

**Screenshots**
Results of the storage, check sequence of storage_content:
```
{'scalars': variable_name
init_content       0.0
invest          1500.0
total           1500.0
Name: 2020-01-01 00:00:00, dtype: float64, 'sequences': variable_name        storage_content
2020-01-01 00:00:00            250.0
2020-01-01 01:00:00            125.0
2020-01-01 02:00:00              0.0
2020-01-01 03:00:00              NaN}
```
**Expected behavior**
```
2020-01-01 00:00:00            0.0
2020-01-01 01:00:00          250.0
2020-01-01 02:00:00          125.0
2020-01-01 03:00:00            0.0}
```

**Desktop (please complete the following information):**
 -   Linux Mint 20.3
 -   Python version 3.9

 - oemof.solph version 0.5.2.dev0  

This might be interesting for you, @nailend

**Comment by p-snft** [comment]
@jokochems: You are right. This looks like it was not updated when we introduced the new indexing. In the result you see what I would have expected with the old (solph v0.4) behaviour. I'll have a closer look.
