### ISSUE TITLE
v0.4.x TypeError on Transformer init with basic example

### ISSUE THREAD

**Issue by wo0lien** [oemof/oemof-solph#1048]
**Describe the bug**
Implementing a Transformer on 0.4.x ( tested on 0.4.4 and 0.4.5) raises a
`TypeError: __init__() got an unexpected keyword argument 'conversion_factors'`

**To Reproduce**
Code :

```python
from oemof import solph

print(solph.__version__)

bgas = solph.Bus(label="natural_gas")
bel = solph.Bus(label="electricity")

tr = solph.Transformer(
        label="pp_gas",
        inputs={bgas: solph.Flow()},
        outputs={bel: solph.Flow(nominal_value=10e10, variable_costs=50)},
        conversion_factors={bel: 0.58, bgas: 0.6},
)
```
**Desktop (please complete the following information):**
 -   OS: (e.g. iOS, Debian, Ubunut, Windows10) : Ubuntu 22.04 in WSL
 -   Python version: 3.9.18 (managed with poetry and pyenv)
 
 I am very likely to miss something really obvious there but I am out of searching options I think.
 Thank you for all the work

**Comment by p-snft** [comment]
Hi @wo0lien, thanks for bringing this up. Version v0.4 of solph requires v0.4 of network, bus it does not define an upper bound for the version. You can `pip install oemof.network==0.4.0` to workaround this problem.
