### ISSUE TITLE
Allow multiple outputs at OffsetConverter

### ISSUE THREAD

**Issue by lensum** [oemof/oemof-solph#1053]
For a project, I need to model a Converter with part-load depending efficiencies that outputs two flows. This is currently not possible with the OffsetConverter. I propose the following changes:

1) `outputs` should be allowed to contain multiple busses. 
2) `coefficients` should expect a dictionary, where the keys are the output busses and the values are the tuples containing the necessary parameters.
3) The issues discussed in https://github.com/oemof/oemof-solph/issues/1010 should be fixed (misleading docu, usage guide and erroneous example).

**Comment by lensum** [comment]
I think the PR or the existing issue are better places for discussion (if necessary), therefore I'm closing this again.

**Comment by p-snft** [comment]
Thanks for bringing this up. IMHO, you should have both, a PR discussing the implementation and an issue discussing the general idea.

About the general idea: There are two possible options to implement something like this. Multiple inputs or multiple outputs. You cannot have both. So, wouldn't it be simpler to just use two `OffsetConverter`s and one `Converter`? This allows the flexibility to do both.

**Comment by lensum** [comment]
If I understand you correctly, you mean that the `Converter` would effectively duplicate the incoming flow (by setting the `conversion_factor` to `1` for each `output`) and these are then fed into the `OffsetConverter`? That might work as well... It would also increase the number of variables, but maybe the pre-solve of efficient solvers would take care of that.

**Comment by p-snft** [comment]
You would have additional variables but code that is a lot easier to maintain. Also, it is a lot more flexible, e.g. allows to combine `OffsetConverter` and `PicewiseLinearConverter`.
