### ISSUE TITLE
The basic_example.py is broken

### ISSUE THREAD

**Issue by fwitte** [oemof/oemof-solph#1070]
It seems https://github.com/oemof/oemof-solph/blob/dev/examples/basic_example/basic_example.py is broken on dev since about two months. It seems the variable naming went wrong there in https://github.com/oemof/oemof-solph/pull/1061. I kind of think, that ChatGPT was confused by `solph.components` and made up `solver_components` ;).

**Comment by p-snft** [comment]
Too bad. I'm sorry for my faulty review. Seems like we need to cautious not to accept copilot BS. (I assume no human being would ever make that kind of a mistake, thus I just overlooked it.)
