### ISSUE TITLE
Remove cellular model stub

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof-solph#1078]
We have an experimental stub for cellular energy system modelling that in my opinion should be replaced by proper filtering of nodes and the labeling system. I suggest removing that stub. Are there objections?

**Comment by p-snft** [comment]
@lensum, as you originally added this, please give feedback.

**Comment by lensum** [comment]
Seeing that this has probably caused more confusion than it brought benefits, I support this motion. 

Unfortunately, I'm hard pressed for time right now, so I might not be able to help much with the removal. From the code-perspective, I think this is mostly the removal of two or three loops in the `Model` (or `BaseModel`) class.
