### ISSUE TITLE
Compare `master` with `dev` in the bagde "commits since ..."

### ISSUE THREAD

**Issue by fwitte** [oemof/oemof-solph#1087]
So you do not need to update the badge with every release.

**Comment by fwitte** [comment]
I by accident pushed to dev in https://github.com/oemof/oemof-solph/commit/5d381b00c49cfa060966cc392f63d876838ec3e4, new badge is working so I guess we just move on? :)

**Comment by p-snft** [comment]
Looks good, thanks. (Should we protect dev from pushes as we protect master?)
