### ISSUE TITLE
Weighted sum optimization method with oemof 0.5.2

### ISSUE THREAD

**Issue by yovitza** [oemof/oemof-solph#1127]
Hello Oemof community, 

I am a new user of Oemof 0.5.2 and now implementing a multi-objective optimization based on the weighted sum method. In this regard, I created several objectives functions. Here are two of those functions: 

1. Maximize cost
2. Minimize emission

_Note: I want to work with more than two objetives functions, then the following structure is better for me to be more flexible._

**Defining the energy system:** 

```
es=EnergySystem()

 bus_diesel=buses.Bus(label="diesel_bus") 
es.add(bus_diesel) 

source_diesel=components.Source(
         label="diesel_source",
         outputs={bus_diesel:flows.Flow(
              variable_costs=0.5,
              custom_attributes={"emission_factor":0.3}
         )}
 )

es.add(source_diesel)

```

**Creating  the combined objective function**

```
weight_cost=0.6
weight_emission=0.4

model=Model(es)

obj_ costs = sum(
         flow.variable_costs * energysystem_base_scenario_model.flow["diesel_source","diesel_bus"]
         for (source, target), flow in energysystem_base_scenario_model.flows.items()
         if hasattr(flow, "variable_costs")
    )

obj_ emission = sum(
         flow.emission_factor * energysystem_base_scenario_model.flow["diesel_source","diesel_bus"]
         for (source, target), flow in energysystem_base_scenario_model.flows.items()
         if hasattr(flow, "variable_costs")
    )
  
combined_objetives=(weight_cost*obj_ costs+weight_emission*obj_ emission)
```

**Optimizing the energy system** 
```
model.objetive=combined_objetives
model.solve(solver="gurobi")


```
**The error I got is:** 

```
KeyError: "Index '('diesel_source', 'diesel_bus')' is not valid for indexed component 'flow'"
```

I have made sure that the flow elements ('diesel_source', 'diesel_bus') exist.

Some questions for the following code lines are:

- Do I need to define _flow_? or it is already created after applying Model(es) ?
- The complete code ran perfectly until I added this set of code lines, showing the error mentioned. 
```

obj_ costs = sum(
         flow.variable_costs * energysystem_base_scenario_model.flow["diesel_source", "diesel_bus"]
         for (source, target), flow in energysystem_base_scenario_model.flows.items()
         if hasattr(flow, "variable_costs")
    )
```

**Comment by p-snft** [comment]
Hi @yovitza, first note that the preferred resource for questions like this is https://forum.openmod.org/tag/oemof-solph

Now to the problem: We use the Node objects, not the strings to index the Flows. So, it should be:

```python
energysystem_base_scenario_model.flow[source_diesel, bus_diesel]
```

**Comment by yovitza** [comment]
> Hi @yovitza, first note that the preferred resource for questions like this is https://forum.openmod.org/tag/oemof-solph
> 
> Now to the problem: We use the Node objects, not the strings to index the Flows. So, it should be:
> 
> ```python
> energysystem_base_scenario_model.flow[source_diesel, bus_diesel]
> ```

@p-snft  thanks so much for your support, clear and concise. It works!
