### ISSUE TITLE
Store results in Components

### ISSUE THREAD

**Issue by simnh** [oemof/oemof-solph#305]
At the moment we do not write back results to components. But I think we should do that. As far as I see it we have the flow value which could be written to `actual_value` and for investment models, we have for example `nominal_value=None` or for storage nominal_capacity = `None`. 

I will do a pull request...I guess..someday

**Comment by ckaldemeyer** [comment]
> At the moment we do not write back results to components. But I think we should do that. As far as I see it we have the flow value which could be written to actual_value and for investment models, we have for example nominal_value=None or for storage nominal_capacity = None.
> 
> I will do a pull request...I guess..someday

This is something I proposed a couple of months ago and it was thought like this in the starting-phase of oemof. In my opinion it is also strongly related to https://github.com/oemof/oemof/pull/297 

Where does this mind-change come from?

**Comment by simnh** [comment]
I do not think I had a mind change :) ...But I think its one step into the right direction (in particular if we use other solving techniques, making the components hold thier results will be an advantage)...and pyomo does it, ebsilon does it, most software as far as I know.

I agree that we should think about this in the general process of result handling. 

I proposed something here just as a reminder, we could just invoke this method somewhere  (instead of the results method for example): 
#307

**Comment by ckaldemeyer** [comment]
> I do not think I had a mind change :) ...But I think its one step into the right direction (in particular if we use other solving techniques, making the components hold thier results will be an advantage)...and pyomo does it, ebsilon does it, most software as far as I know.
> 
> I agree that we should think about this in the general process of result handling.

To me this is absolutely in line with the OOP principle (data encapsulation, ...) and would solve many problems we have been discussing about over and over, again. I would support this :+1: 

And then it would still be possible to create a data structure (multi-index, xarray, ...). Maybe then (individual) components or generally nodes can also have individual functions to write their required results..

**Comment by simnh** [comment]
Nice...

>  Maybe then (individual) components or generally nodes can also have individual functions to write their required results..

We can try, but I think there might be some challenges. To begin, I guess it would be enough to store everything that is stored in the result dict in the components by one function...

Only thing missing is the storage level, as there is no corresponding argument in the input...though we could provide it, in this way it would (could) also be clear that a variable is derived from the argument.

**Comment by ckaldemeyer** [comment]
> Nice...
> 
> Maybe then (individual) components or generally nodes can also have individual functions to write their required results..
> We can try, but I think there might be some challenges. To begin, I guess it would be enough to store everything that is stored in the result dict in the components by one function...
> 
> Only thing missing is the storage level, as there is no corresponding argument in the input...though we could provide it, in this way it would (could) also be clear that a variable is derived from the argument.

We could just be specific and add it in the network class. Or what do you mean?

**Comment by uvchik** [comment]
It is very important, that we do have a clear results API. We talked about that at the last developer meeting. We should come to a decision. As the user community is increasing we should be clear in that point.

The developer meeting would be nice to finalise the results API, but at the next meeting we are very few developers. Shall we hold a web meeting?

**Comment by ckaldemeyer** [comment]
> It is very important, that we do have a clear results API. We talked about that at the last developer meeting. We should come to a decision. As the user community is increasing we should be clear in that point.
> 
> The developer meeting would be nice to finalise the results API, but at the next meeting we are very few developers. Shall we hold a web meeting?

:+1: Sound good to me. What about Thursday or Friday? I am quite busy atm since I have a meeting and presentation on Wednesday..

**Comment by uvchik** [comment]
This is set to the 'Nice to have' milestone. As we will have a new results API in v0.2.0 I am not sure if this is really nice to have.

@oemof/oemof-developer-group Is anybody still interested in this option? For v0.2.x we agreed on a new results API. Therefore the only option is to implement it on top of the new API.

**Comment by p-snft** [comment]
As this was not touched for years now, I will close the issue.
