### ISSUE TITLE
Plausibility test

### ISSUE THREAD

**Issue by simnh** [oemof/oemof-solph#390]
I transferred this from the wiki, which seemed to be forgotten: 

Here are some quick ideas to start with (any further suggestions are welcome):

### Bus balances

* check if zero for all timesteps (regarding a small deviation "epsilon")
    
### Transformers

* Check if outputs divided through their efficiency equal their input for all timesteps
* Check if full load hours are between 0 and 8760
 
### Storages

* Check storage balance over time (sum(inflow)>sum(outflow))
* Check if SOC(t=0) is SOC(t=t_max)

### Merit-Order-Checks

* Check if or der sort(marginal_prices) equals order of sort(full load hours)
* Merit-Order plots (price vs. quantity): Check if all transformers on the right side of the required quantity (demand) are zero

**Comment by p-snft** [comment]
Not needed as we have constraint tests.
