### ISSUE TITLE
Allow simple array for timeindex  for energysystem / solph model

### ISSUE THREAD

**Issue by simnh** [oemof/oemof-solph#457]
I think modelling should also work if a simple list as index is passed, if for example temporal aggregation by clustering methods is performed, there are no 'real days' anymore.

**Comment by uvchik** [comment]
I would keep the datetimeindex as the default way but allow Series/Array/(lists?).

**Comment by busiing** [comment]
Self-assignment due to oemof dev meeting - issue auction

**Comment by p-snft** [comment]
This is maybe to be considered in #586.

**Comment by p-snft** [comment]
This is pretty old and not compatible with our new way to handle time. Closed.
