### ISSUE TITLE
Result API : View of nodes with no scalar results (key error) 

### ISSUE THREAD

**Issue by simnh** [oemof/oemof-solph#461]
Atm the moment, if no scalars exist for the results the key does not exist for views of a node. Could me add the the key even if there are no results but add an empty frame or something else. I think this would make processing easier.

**Comment by ckaldemeyer** [comment]
> Atm the moment, if no scalars exist for the results the key does not exist for views of a node. Could me add the the key even if there are no results but add an empty frame or something else. I think this would make processing easier.

It was implemented like this in the beginning and I have removed it due to the redundancies (cumulating in postprocessing when series without data are added, etc.). I think it is a bit cleaner when empty series are not included. But feel free!

**Comment by ckaldemeyer** [comment]
I think it would be two lines to be added if we decide it and if there are reasons to change it we should do it!

**Comment by simnh** [comment]
Mh...I don't know, if you see disadvantages...I will check in the future. We are currently working on a results to datapackage function. I will see if it annoys us to much... 

Lets wait for other opinions here

**Comment by ckaldemeyer** [comment]
> Mh...I don't know, if you see disadvantages...I will check in the future. We are currently working on a results to datapackage function. I will see if it annoys us to much...

I think a homegenous data structure would of course provide advantages within a postprocessing. As we have often hindered ourselves in the developing process and this does not change the API, go ahead if we have some opinions here or if no one cares (my opinion)!

**Comment by jnnr** [comment]
This issue seems to have rested for a while. Are there any new thoughts/opinions? New comments after oemof_tabular has been released, @simnh ? From my point of view: I have no strong opinion in favour for either side, but would be ok to go along if there are good arguments.

**Comment by p-snft** [comment]
As nobody interacted with this for more than three years, I will close this.
