### ISSUE TITLE
Docstring of GenericInvestmentStorageBlock

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-solph#479]
The docstring seems inconsistent. Shouldn't it be `om.GenericInvestmentStorageBlock.capacity` and `om.GenericInvestmentStorageBlock.invest?`

> **The following variables are created:**
> 
>     capacity :attr:`om.InvestmentStorage.capacity[n, t]`
>         Level of the storage (indexed by STORAGES and TIMESTEPS)
> 
>     invest :attr:`om.InvestmentStorage.invest[n, t]`
>         Nominal capacity of the storage (indexed by STORAGES)
> 

The following, described at the end of the docstring, also does not work for me. There is no attribute om.InvestStorages. Am I doing something wrong?

> The expression can be accessed by :attr:`om.InvestStorages.investment_costs` and their value after
> optimization by :meth:`om.InvestStorages.investment_costs()` .

**Comment by uvchik** [comment]
You are right, it does not work this way. We could change it:

```diff
- capacity :attr:`om.InvestmentStorage.capacity[n, t]`
+ capacity `om.InvestmentStorage.capacity[n, t]`
```

**Comment by jnnr** [comment]
The respective parts have been changed, therefore I close this issue.
