### ISSUE TITLE
Core refactoring

### ISSUE THREAD

**Issue by simnh** [oemof/oemof-solph#502]
**Edge class**

- [x] Currently the edge class is kind of hidden in core. This should be changed including it's str representation (ie. 'from -> to'), see #521
- [x] Allow connection from bus to bus: Addressed in #548
- [ ] Add xarray-dataset for energy system
  * The graph structure should be transfered to xarray. API would then look like this: 
``` 
es.nodes.loc['supplies'] 
es.edges
 ```

**Comment by gnn** [comment]
Sure. PR #506 goes along with this.

**Comment by p-snft** [comment]
As #521 is merged, is this resolved then?

**Comment by simnh** [comment]
I think this can be closed
