### ISSUE TITLE
Solver delivers status="ok/warning" and termination_criterion="infeasibleOrUnbounded/infeasible"

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof-solph#512]
There are situations where the **CBC** solver delivers the flags "ok" and "infeasibleOrUnbounded" as status and termination criterion whereas **Gurobi** delivers "warning" and "infeasible".

Both cases are not caught explicitly but treated in the general else part within [models.py](https://github.com/oemof/oemof/blob/dev/oemof/solph/models.py#L207).

I just stumbled across this when I was tracing down why there were still results for infeasible problems in another context.

The following minimal examples illustrates the behaviour (don't look sharply at the problem, it is only meant to produce feasible problems and have an unfeasible in between):

	from pyomo.environ import (ConcreteModel, Set, Param, Var, Constraint,
		                   Objective, Binary)
	from pyomo.environ import maximize
	from pyomo.opt import SolverFactory

	# Data
	T = [1, 2, 3, 4]
	Cel = [20, 20, 20, 20]
	Pmax = [30, 30, 30, 30]

	# Create model
	m = ConcreteModel()

	# Sets
	m.T = Set(initialize=T)

	# Variables
	m.P = Var(m.T, bounds=(0, 100))

	# Params
	m.Cel = Param(m.T, initialize=dict(zip(T, Cel)))
	m.Pmax = Param(m.T, initialize=dict(zip(T, Pmax)))

	# Constraints
	def max_rule(model, t):
	    return(m.P[t] >= m.Pmax[t])
	m.max = Constraint(m.T, rule=max_rule)

	# Objective
	def obj_rule(model):
	    return(sum(m.Cel[t]*m.P[t] for t in m.T))
	m.profit = Objective(sense=maximize, rule=obj_rule)

	# m.pprint()

	# results should only be loaded if optimization has terminated successful
	for i in [40, 35, 25, 40]:

	    for t in T:
		m.P[t].setub(i)

	    # Define Solver
	    opt = SolverFactory('gurobi')

	    # Solve the model
	    results = opt.solve(m, tee=False)

	    #print(type(results), dir(results))
	    status = results["Solver"][0]["Status"].key
	    termination_condition = results["Solver"][0]["Termination condition"].key

	    print(status, termination_condition)

	    # # Load results back into model
	    # m.solutions.load_from(results)

	    # Print results
	    print([m.P[t].value for t in T])
	    results = None

This was more for information as the error gets treated as explained above. But we might want to catch this error explicitly as we have **CBC** as default solver in all examples..

**Comment by uvchik** [comment]
Do I get it right? The problem is, that the solver returns the status "ok" but as the problem is infeasible, so there won't be any results, right?

Is it a MILP problem or does it occur in LP models as well (as far as you know)?

One reason could be a misinterpretation of a cbc message in pyomo.

As my first statement is right and  "infeasibleOrUnbounded" means no results I would just extend the logging message with something like: "In some cases the cbc solver returns the status 'ok', even though the problem is infeasible. Don't be confused."

**Comment by ckaldemeyer** [comment]
> Do I get it right? The problem is, that the solver returns the status "ok" but as the problem is infeasible, so there won't be any results, right?

The model (which one just has to keep in mind) holds still the results of the last (successful) calculation even of the results are not explicitly written back (as we do it in oemof).

> Is it a MILP problem or does it occur in LP models as well (as far as you know)?

This has to do with the model object and is not related to the problem type.

> One reason could be a misinterpretation of a cbc message in pyomo.

Yes, this is most likely the case we could test it by exporting an LP and solving it directly. But as we are tied to Pyomo, I just propose to deal with it somehow if we can agree on a solution.

> As my first statement is right and "infeasibleOrUnbounded" means no results I would just extend the logging message with something like: "In some cases the cbc solver returns the status 'ok', even though the problem is infeasible. Don't be confused."

Another idea: we could also catch only the warnings of the solver status and log that the model and results have to be checked and use the same message for the case that the status is "ok" and the termination criterion is not "optimal". This way, we only give back "optimization successful" if everything has worked fine and all the other stuff (logging.warning("Optimization might be sub-optimal.", ...) is captured as well or we leave it as it is.

I guess it is also just a naming thing with the solver status, termination, ... within `SolverFactory()` but to me just wasn't intuitive..

**Comment by ckaldemeyer** [comment]
> The model (which one just has to keep in mind) holds still the results of the last (successful) calculation even of the results are not explicitly written back (as we do it in oemof).

So basically there are two things I noticed:

1.) The result behaviour when solving multiple times and having infeasible models in between (see above).
2.) The flags which are delivered back and did not seem intuitive for me, even if they are treated correctly.

Hope this makes it clearer ;-)

**Comment by p-snft** [comment]
Interest seems to be lost.
