### ISSUE TITLE
Namedtuple-Labels are not preserved within energysystem.groups

### ISSUE THREAD

**Issue by henhuy** [oemof/oemof-solph#517]
I sometimes look up `Nodes` by their label from `energysystem.groups`. Nowadays, I use `collections.nemadtuple` to create my labels, but I had to figure out that those namedtuples are not preserved in the `energysystem.groups` dict, but are replaced with their `__str__`-representation.

Is this behaviour intended? Should I look it up elsewhere? Or should we change code to support preservation of namedtuple-labels?

**Comment by uvchik** [comment]
I stumbled over the same issue. I agree that it is more intuitive if the key is the object. 

If you use the your own object without `__str__` representation you get something like `<your_class object at 0x109b73da0>` where the object id is not robust. You will not be able to find the group element. 

Most people use string keys and they will not see a difference, but it will break the API.

**Comment by p-snft** [comment]
Interest seems to be lost.
