### ISSUE TITLE
ForeignKeys in objects for edge parameters in the datapackage reader

### ISSUE THREAD

**Issue by simnh** [oemof/oemof-solph#520]
I encountered some problems when setting timedependent parameters via a json object:

Setting this on in a field  `{'max': max_profile}` and then having an additional resource where `max_profile` is on field containing the data. The datapackage reader should be able to resolve this. However, I could not make this work...

@gnn do you know how the meta data foreignKey has to be specified?

**Comment by p-snft** [comment]
Interest seems to be lost.
