### ISSUE TITLE
Flow / Edge values do not match after component update 

### ISSUE THREAD

**Issue by simnh** [oemof/oemof-solph#542]
I am updating my components with new values, for example the variable cost:

As an example I have 40 for the variable costs first  and 200  to be updated. After I change this value 
these two calls give different results: 

Yield new updated value: 
`[i for i in es.groups['gas-gt'].outputs.values()][0].variable_costs[0]` -> 200

Yields old one: 
`m.flows[(es.groups['gas-gt'], es.groups['bus1'])].variable_costs[]` -> 40

The problem is, that this `m.flows` is based on es.flows() method, which is fundamental for solph, and currently the update option for the obejective function expression does not work anymore due to the behavior.

Can you fix this @gnn?

**Comment by uvchik** [comment]
What about this? Is it solved. I will postpone it to v0.3.1

**Comment by p-snft** [comment]
Nobody talked about this ever since. I will close this.
