### ISSUE TITLE
Prevent `Edge` labels from being erroneously tampered with

### ISSUE THREAD

**Issue by gnn** [oemof/oemof-solph#545]
The need to [prevent `solph` from assigning a label][0] when doing attribute mass assignment uncovered the fact that I need to put in extra checks to prevent this from happening. Also, some documentation stating that `Edge` labels get automatically generated from their inputs and outputs would be nice.

[0]: https://github.com/oemof/oemof/commit/69a672efc7a81ea81c452ad1fafe88c9de74d502

**Comment by uvchik** [comment]
I still will be able to pass a label attribute to the flow but it will be ignored in the first step and label will be added automatically in the next step. Do I get it right?

Shouldn't we raise a warning if somebody passes a label attribute instead of just 'swallow' it.

**Comment by gnn** [comment]
The label will be completely ignored and a different one will always be automatically generated, namely a `namedtuple` containing the `input` and the `output`. Btw. this might seem like a breaking backwards compatibility, but this is merely by accident. Originally, `Flow`s were a standalone class, so `label`s didn't have any special meaning for them. Usually, one wouldn't even put one on them as there was no `label` parameter for the constructor. So you would've to manually set a new `label` attribute on every `Flow` instance for which you wanted to have one. Basically, when I integrated `Flow`s as first class citizens into `EnergySystem`s, I made the mistake of not caring enough for how `label`s are handled and this issue is a reminder for me to do that in the near future.
Concerning the warning: I'd not only generate one but straight up raise an error. That's what I meant with "extra checks".
Concerning how labels would be handled: I can either disallow specifying a `label` for an `Edge`, or I can incorporate a given `label` into the one that will be generated. I'm leaning towards the first solution because if I do, allowing them and handling them specially would be a backwards compatible change.

**Comment by uvchik** [comment]
> Concerning the warning: I'd not only generate one but straight up raise an error. That's what I meant with "extra checks".

:+1: You are right. Raising an error is the better way.

**Comment by p-snft** [comment]
Is this still relevant?

**Comment by p-snft** [comment]
Has been solved at network level: https://github.com/oemof/oemof-network/pull/43 (We were a bit more radical, as every `Entity` now has an immutable label.)
