### ISSUE TITLE
Missing documentation oemof/solph/constraints.py

### ISSUE THREAD

**Issue by oakca** [oemof/oemof-solph#555]
https://github.com/oemof/oemof/blob/dev/oemof/solph/constraints.py

Under the function `equate_variables()` there is a documentation about how to use that function.

```
    >>> bel1 = solph.Bus(label='electricity1')
    >>> bel2 = solph.Bus(label='electricity2')
    >>> energysystem.add(bel1, bel2)
    >>> energysystem.add(solph.Transformer(
    ...    label='powerline_1_2',
    ...    inputs={bel1: solph.Flow()},
    ...    outputs={bel2: solph.Flow(
    ...        investment=solph.Investment(ep_costs=20))}))
    >>> energysystem.add(solph.Transformer(
    ...    label='powerline_2_1',
    ...    inputs={bel2: solph.Flow()},
    ...   outputs={bel1: solph.Flow(
    ...       investment=solph.Investment(ep_costs=20))}))
    >>> om = solph.Model(energysystem)
    >>> line12 = energysystem.groups['powerline_1_2']
    >>> line21 = energysystem.groups['powerline_2_1']
    >>> solph.constraints.equate_variables(
    ...    om,
    ...    om.InvestmentFlow.invest[line12, bel2],
    ...    om.InvestmentFlow.invest[line21, bel1])
```

`bel1` -- `input.Flow()` --> `line12` -- `output.Flow()` --> `bel2`
`bel2` -- `input.Flow()` --> `line21` -- `output.Flow()` --> `bel1`

If you use investment mode on `input.solph.Flow()` instead of `output.solph.Flow()`, then the `equate_variables()` function should be transformed as follows:

```
 >>> solph.constraints.equate_variables(
    ...    om,
    ...    om.InvestmentFlow.invest[bel1, line12],
    ...    om.InvestmentFlow.invest[bel2, line21])

```

This can be added to documentation under the function.

**Comment by jakob-wo** [comment]
The documentation of `equate_variables()` can now be found in the [oemof.solph docu](https://oemof-solph.readthedocs.io/en/latest/reference/oemof.solph.html#oemof.solph.constraints.equate_variables).

**Comment by p-snft** [comment]
Looks like this is done.
