### ISSUE TITLE
Allow import xor export

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof-solph#567]
Consider the the situation where energy export is more profitable than own consumption, but there is just one power meter. I found the [transshipment example](https://github.com/oemof/oemof-examples/blob/dev/oemof_examples/oemof.solph/v0.3.x/electrical/transshipment.py) that seems to address this issue. However, it seems to allow importing and exporting at the same time, see [single-meter.py](https://gist.github.com/p-snft/21793ecfeba9467a9624344c9f5724de). Is this by design or is this custom component just incomplete in this respect?

**Comment by p-snft** [comment]
There are two possible solutions to my original problem:
1. Allow a parameter in `custom.Link` that lets you set xor. Such a parameter might be called e.g. `single_line`.
2. Have a combined sink/source (e.g. `GridConnectionPoint`) that can serve as Sink or Source at different points in time.

While the first option would be more flexible, the second one would probably be faster to compute. I want to consider feedback but I also have to decide until the end of the week.

**Comment by ckaldemeyer** [comment]
Do you need to implement this as a component or would it also be sufficient to add respective constraints?

Anyhow, as far as I know an `XOR` relation between variables i.e. flows can only be modelled by means of binary variables which automatically leads to a `MIP`. It would be easy to implement but be costly in terms of possible solution time. Nevertheless, this relation of flows would keep the directional nature of the graph.

Another possibility would be to change the domain of the flow from `NEG_LB <= FLOW <=POS_UB` so that the direction would indicate the direction of the flow. But this would break the direction and I also cannot estimate the consequences as it might impact other constraints such as runtimes, etc. So I would discard this option..

To cut a long story short I would be fine with both of your proposals with a tendency to the first option.

**Comment by ckaldemeyer** [comment]
I guess @uvchik and @simnh might have a stronger opinion here!

**Comment by simnh** [comment]
I agree with the binary MILP stuff @ckaldemeyer  said. However, the flow problem does not exist. We already have flows implemented like this. There is a set 'BIDIRECTIONALFLOW' https://github.com/oemof/oemof/blob/dev/oemof/solph/models.py#L283-L286 in the model. We use this in the ElectricalLine https://github.com/oemof/oemof/blob/dev/oemof/solph/custom.py#L44-L99 component where we subclass from Flow (which is also a Node like other Components)

**Comment by ckaldemeyer** [comment]
> There is a set [BIDIRECTIONALFLOW](https://github.com/oemof/oemof/blob/dev/oemof/solph/models.py#L283-L286) in the model. We use this in the [ElectricalLine](https://github.com/oemof/oemof/blob/dev/oemof/solph/custom.py#L44-L99) component where we subclass from Flow (which is also a Node like other Components)

Oh, cool. I haven't used it yet. Does this work with all capabilities e.g. min-uptimes, ... ?

Of course it is possible to implement different logics. For me the question would more be if new implementations are in line with the overall concepts i.e. graph based modelling.

**Comment by ckaldemeyer** [comment]
> There is a set [BIDIRECTIONALFLOW](https://github.com/oemof/oemof/blob/dev/oemof/solph/models.py#L283-L286) in the model. We use this in the [ElectricalLine](https://github.com/oemof/oemof/blob/dev/oemof/solph/custom.py#L44-L99) component where we subclass from Flow (which is also a Node like other Components)

A, now I understand. This already solves @p-snft 's problem!

**Comment by p-snft** [comment]
Actually, the "angle formulation" part of the docstring in combination with the large number of TODOs made me skip the ElectricalLine.

I also do understand @ckaldemeyer's concerns that `BIDIRECTIONAL_FLOWS` break with the concept of the directed graph. However, they seem to be a fast (in terms of computational time) solution. In a directed graph environment, the combined Sink/Source would be cleaner. So, I wonder if `BIDIRECTIONAL_FLOWS` will have to stay custom components or if it makes sense to generally allow undirected graphs (the default `min` might still be set to 0).

I will now try to work with the `ElectricalLine` and hope it's Ok to ignore some of its features.

**Comment by ckaldemeyer** [comment]
> I also do understand @ckaldemeyer's concerns that `BIDIRECTIONAL_FLOWS` break with the concept of the directed graph. However, they seem to be a fast (in terms of computational time) solution. In a directed graph environment, the combined Sink/Source would be cleaner. So, I wonder if `BIDIRECTIONAL_FLOWS` will have to stay custom components or if it makes sense to generally allow undirected graphs (the default `min` might still be set to 0).

Maybe this would be a good topic for the meeting in May?

> I will now try to work with the `ElectricalLine` and hope it's Ok to ignore some of its features.

Keep us up to date!

**Comment by p-snft** [comment]
> Maybe this would be a good topic for the meeting in May?

Good idea, I added the topic at [Meeting-May-2019#directed-or-mixed-graph](https://github.com/oemof/organisation/wiki/Meeting-May-2019#directed-or-mixed-graph).

**Comment by p-snft** [comment]
A component that would help solving the problem was a circulator (typically used for RF, low frequency design see e.g. [Richard, 2001](https://www.edn.com/design/analog/4343519/Circuit-forms-low-frequency-circulator). In combination with the bidirectional flow, it would allow to design import xor export.

In fact, I see many applications for a generalized circulator component that allows to have different feed-though efficiencies between ports. A simple example would be a generator that can use various fuels at different efficiencies. (For that example, you could also have transformers before the input but it would be more straightforward to have it inside the object modelling the physical component.)

**Comment by ckaldemeyer** [comment]
> **Edit 1**: I had to realize that `BIDIRECTIONAL_FLOWS` do net help me. I have to set a different price for import and export. Though, for the specific problem, I found a workaround. (It is based on not modelling the actual cabling. Instead, I let both import and export merge in one flow that is limited so that just one option can be taken at the same time.)
> 
> **Edit 2**: The workaround does not help either. It depends on knowing the internal production which is not given in all cases.

What about assigning slightly transmission losses or costs for one of either? Wouldn't this solve the problem?

**Comment by ckaldemeyer** [comment]
> A component that would help solving the problem was a circulator (typically used for RF, low frequency design see e.g. [Richard, 2001](https://www.edn.com/design/analog/4343519/Circuit-forms-low-frequency-circulator). In combination with the bidirectional flow, it would allow to design import xor export.
> 
> In fact, I see many applications for a generalized circulator component that allows to have different feed-though efficiencies between ports. A simple example would be a generator that can use various fuels at different efficiencies. (For that example, you could also have transformers before the input but it would be more straightforward to have it inside the object modelling the physical component.)

I you think this is useful, you are very welcome to implement it!

**Comment by p-snft** [comment]
With the existing components, I do not see any possibility to model a situation where concurrent export and import are profitable but physically impossible. Adding losses would get me to a case where the export margin is no longer higher than the import costs.

According the component: I hoped to get some advice, but probably I should just start drafting it.

**Comment by ckaldemeyer** [comment]
> With the existing components, I do not see any possibility to model a situation where concurrent export and import are profitable but physically impossible. Adding losses would get me to a case where the export margin is no longer higher than the import costs.
> 
> According the component: I hoped to get some advice, but probably I should just start drafting it.

:+1:

**Comment by simnh** [comment]
If the component can be constructed out of multiple existing component and does not require new equations, oemof-tabular facades module... Where we try to collect energy system specific user friendly components.. The reservoir component would be an example in this repository.. But I think, you are looking more for a new component which can not be build out of connecting and parameterizing existing ones

**Comment by p-snft** [comment]
Result of oemof meeting: An additional constraint would be more elegant and faster.

**Comment by joroeder** [comment]
hey, I wonder, has this been realized yet or does anybody has an example for that constraint? One of my project colleagues is interested in such a constraint for avoiding charging and discharging of a storage at the same time.

**Comment by p-snft** [comment]
For the time being I worked with my Switch component. If there is interest, it should be rather simple to do it properly. I should find some time tomorrow.

**Comment by joroeder** [comment]
Okay thanks. Though, from my side there is no hurry. We could support you as good as we can, at least doing documentation, test, ... @RD-OTH, what do you think?
...but probably I won't have enough time this week and then I will be on holiday for two weeks.

**Comment by p-snft** [comment]
> Another possibility would be to change the domain of the flow from `NEG_LB <= FLOW <=POS_UB` so that the algebraic sign indicates the direction of the flow. But this would break the directional nature and I also cannot estimate the consequences as it might impact other constraints such as runtimes, etc. So I would discard this option..

To have this documented, now that the (generalized) XOR (#623) is nearly implemented: I even considered a "Balancer" component that would act as a Sink or Source depending on whether inflow or outflow dominates. This would be somewhat like a storage with infinite capacity and no losses. However, as soon as I start pricing destruction and creation inside that component independently, I see me ending up with a binary problem. So, there should be no benefit compared to the more generic XOR.

**Comment by p-snft** [comment]
Resolved by #623.
