### ISSUE TITLE
Handling of variables that are not connected to a component or flow

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof-solph#630]
I opened an issue because the problem occurred in two different PRs. 

In PR #623 a variable is defined together with an addition constraint. This variable is neither connected to a component nor to a flow. In [line 30](https://github.com/oemof/oemof/blob/dev/oemof/outputlib/processing.py#L30) in the processing module the information of the variable is extracted. This used to be a tuple, that includes the component or the flow (from_component, to_component) or the component itself. In PR #623 there is no component but just the name of the constrain.

In PR #592 the variable is not created by solph but by pyomo with the peacewise() function. The name of this variable does not have any information about the component but the name of the block-class `PiecewiseLinearTransformerBlock`.

In both cases the [get_tuple()](https://github.com/oemof/oemof/blob/dev/oemof/outputlib/processing.py#L23) function returns `None`. But `None` will lead to an error later on, so there was the idea to remove all lines with a  `None` afterwards. This helps to avoid the error but we will not be able to find the value of the variable in the results.

What can we do?

I think the first case is a bit easier because we have full control over the name of the variable. We could create an constrained_name object and use it instead of the name. Afterwards we can check in the `get_tuple` function if such an object exists and create a well defined tuple as a key in the results dictionary.
In the second case we do not have full control over the name of the variables. And the format of this variable differs from typical solph variables.

Below you see line 72-79 from the processing module:
```python
block_vars = []
    for bv in om.component_data_objects(Var):
        block_vars.append(bv.parent_component())
    block_vars = list(set(block_vars))

    # write them into a dict with tuples as keys
    var_dict = {(str(bv).split('.')[0], str(bv).split('.')[-1], i): bv[i].value
                for bv in block_vars for i in getattr(bv, '_index')}
```

The problem is the `.split('.')` method. In most case we get a list of one or two elements. In case of one element both expression (`str(bv).split('.')[0]` and `str(bv).split('.')[-1]`) will return the same result. In case of two elements the result will be different. But in case of three elements the element in the middle will not be kept. But in case of the piecewise variable we do have three elements and the middle element contains the information about the class and is very important.

**Comment by p-snft** [comment]
Any good ideas for a general approach?

We could just default to memory addresses, as it is done for components without given labels. This is rather ugly but at least solve (only workaround?) the problem.

**Comment by p-snft** [comment]
I found that in #623, there is already a usable variable name. It is just dropped as there is no nested tuple that can be extracted by `get_tuple(x)`. I adjusted the processing accordingly, so that now a fitting tuple is created based on the existing name. (See also [oemof_examples:flow_count_limit](https://github.com/oemof/oemof-examples/blob/features/max_active_flow_count/oemof_examples/oemof.solph/v0.3.x/flow_count_limit/flow_count_limit.py).)
