### ISSUE TITLE
Test of a pep8 checker

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof-solph#635]
If review a PR we also have to check if the developer followed the PEP8 rules. This annoying because we want to focus on the content.

There are several tools that check the code for PEP8 issues and informe the contributor about problems.

I would like to test one of these checkers. If no one objects I will install it. After we made some experience we can decide whether we want to keep it.

https://github.com/OrkoHunter/pep8speaks

**Comment by p-snft** [comment]
Thanks for bringing this up. Please do so!

**Comment by uvchik** [comment]
I think i added pep8speaks and LGTM to oemof. Let us see how it works and whether it is helpful or annoying.

@oemof-developer Please give feedback according LGTM and pep8speakes to this issue.

**Comment by p-snft** [comment]
LGTM seems not to be fully included. As I really like the kind of advice, I just sent a request to install the according app for oemof at GitHub.

**Comment by gnn** [comment]
Ah, I see you're integrating this via GitHub apps. In `oeomf.tabular` we're using `flake8` by having it integrated into our test suite, so it's ran by Travis. Flake8 also warns about unused imports but I'm pretty sure LGTM also does other things flake8 doesn't.

**Comment by jnnr** [comment]
In oemof-thermal we use both flake8 and pylint in combination.

**Comment by uvchik** [comment]
It is obsolete and will be discussed in the unbundling process...
