### ISSUE TITLE
Docs could use a review

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-solph#646]
This issue is related to tespy's https://github.com/oemof/tespy/issues/87

1. Check for a consistent structure
2. update old information, repair broken links and fix errors,
3. fill a glossary.

We aim to tackle this one at the next [oemof-dev meeting](https://github.com/oemof/organisation/wiki/Meeting-December-2019)

**Comment by jnnr** [comment]
Related issues in oemof-solph on docstrings
#596 #479

**Comment by jnnr** [comment]
Agenda for that issue (adapted from tespy docs review)

**Documentation in oemof/doc**

In the online documentation we need to check for

- typos,
- comprehensibility (would a new user understand the main ideas?) and
- structure (does the structure of the chapters help the user understand how to use oemof-solph?).

- [ ] Getting started
- [ ] About oemof
- [ ] Installation and setup
- [ ] Using oemof
- [ ] Developing oemof
- [ ] oemof-network
- [ ] oemof-solph
- [ ] oemof-outputlib
- [ ] oemof-tools

The same criteria should be checked in:

- [ ] README.rst

**Docstrings and inline comments**

In the doc-strings and the inline comments we need to check for the following:
- Are there any typos?
- Are the examples well-formatted, correct and comprehensible?
- Is information well placed (are the equations and parameters apparent)?
- Are the links in the doc-strings working?
- Are the inline comments clear?

- oemof/outputlib
  - [ ] processing.py
  - [ ] views.py

- oemof/solph
  - [ ] blocks.py
  - [ ] components.py
  - [ ] constraints.py
  - [ ] custom.py
  - [ ] groupings.py
  - [ ] models.py
  - [ ] network.py
  - [ ] options.py
  - [ ] plumbing.py

- oemof/tools/
  - [ ] economics.py
  - [ ] helpers.py
  - [ ] logger.py

- [ ] energy_system.py
- [ ] graph.py
- [ ] groupings.py
 - [ ] network.py

**Comment by joroeder** [comment]
Do we want to have consistent AE or BE?

**Comment by jnnr** [comment]
# Getting started
> Contribution is already possible on a low level
 Workflow could be described in more detail.

## Installing oemof 
Installing oemof is double: In getting started and in installation and setup.

## Structure of the oemof cosmos
Hard to read. Bullet points would be more readable. Could be include the figure showing the layers from Hilpert 2018? This section could be moved somewhere else if oemof and solph would be unbundled.

**Comment by jokochems** [comment]
It would be quite nice if there was at least a link to the constraints resp. target function elements for the basic solph components in the oemof solph docu itself, not only in the API description. This is given for some of the custom components, but not for the basic ones.

**Comment by uvchik** [comment]
Some of the comments are outdate because the structure changed due to the unbundling but we could keep it open to check if everything is done.

**Comment by p-snft** [comment]
This is an evergreen. Still (or because of this), I will close this issue.
