### ISSUE TITLE
Improve documentation of GenericCHP

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof-solph#648]
As we got some questions concerning parameters such as Beta, etc. via the mailing list, we should improve the documentation in order to make the functionality more transparent:

* Add underlying paper of Mollenhauer et al. already in the general documentation and not only within the class documentation
* Outline calculation of relevant parameters such as Beta i.e. "Stromverlustkennziffer" already within the documentation by porting them from the paper e.g. from equation 3 on page 3 in this case

Maybe we can add a simple PR on the dev-meeting and fix it for the next version..

**Comment by p-snft** [comment]
As this is targeted for 0.4, you should also consider to use more talking names (e.g. `power_loss_factor` instead of `beta`). For the formulas, you would still use the beta, so it can be easily identified with the corresponding one from the paper.

**Comment by jnnr** [comment]
To add another observation: I just noticed that in the case of a backpressure turbine, the 'without district heating' specification in `Eta_el_max_woDH`, `Eta_el_min_woDH` is quite confusing.

**Comment by uvchik** [comment]
We should also have a look at the symbols used in `ExtractionTurbineCHP`. We could use the same terms if they are the same in both classes. It doesn't matter if we change it in `GenericCHP` or in `ExtractionTurbineCHP` as long as they are the same.

**Comment by jnnr** [comment]
Another observation: The order of equations, parameter table, figure and code snippets is changed comparing between the ExtractionTurbineCHP and GenericCHP.

I would find the following order natural and good to read:

1. figure
2. equations
3. parameter table
4. code snippets
5. (plots of results)

The figure gives an immediate impression, the equations tell the concept, next would be the parameter table if you want to look up what some parameter means, then the code snippets that show how to use the component.

**Comment by uvchik** [comment]
Is this fixed by #677?

**Comment by p-snft** [comment]
Seems not to be an issue anymore.
