### ISSUE TITLE
Next major release v0.4.0

### ISSUE THREAD

**Issue by joroeder** [oemof/oemof-solph#669]
This issue plans and discusses the next major release. As discussed at the last dev meeting, there is the plan to do the unbundling of oemof #639  with the v0.4.0 release.
Another thing is some API changes at the GenericStorage, which have been discussed for a long time #538 

I would suggest 8 April 2020 as release date - this would be a month before the next user/dev meeting (13.-15 May 2020). What do you think?

There is always the option of doing a minor release (v0.3.3) before the next major release, if you want to have a feature released and don't want to wait that long. Please check your v0.3.3 milestones of your PRs and issues and adapt them accordingly.

**Comment by joroeder** [comment]
The plan is to release v0.4.0 in the first week of May.

@oemof/oemof-developer-group  @oemof/oemof-solph
* Please finish and merge all PRs, you want to release with v0.4.0, until **30.04.2020**
* Please change the milestone of your PR accordingly to **v0.4.0**, or to **v0.4.1**, if you think you won't manage to merge by end of April.

Thanks!

**Comment by jnnr** [comment]
I talked to @uvchik last week and we agreed that it would be good if we can include #680 in the v0.4.0, as it includes a change of the api. There is still some work to do however. We agreed that I will transfer the changes to a new branch to save work related to resolving merge confllicts and @uvchik will take some time to have a look at it as well, as he already put some thought into it. We hope to see some progress this week. Just to let you know that this is open and we would like to include it!

**Comment by uvchik** [comment]
There are still 24 issues with the [milestone `v0.3.3`](https://github.com/oemof/oemof-solph/milestone/23). Please check if you are assigned and change the milestone!

**Comment by uvchik** [comment]
There are still 15 issues/PR with the [milestone v0.4.0](https://github.com/oemof/oemof-solph/milestone/21) but the release date was 5 days ago. We will postpone the release to the next week but please finish your work or postpone/close your issue/PR.

**Comment by joroeder** [comment]
Dear all,

the v0.4.0 has been released 👏 🍻 🎉😊

oemof-solph can be installed with ```pip install oemof.solph```

Can somebody write a wordpress notice? 😉

For further developments, there will be slight change than before:
* always branch from the ``dev`` branch. It does not matter if you do not know yet, if you are going to break the API.
* There will be already a ``v0.5.0`` branch. So, if you break the API, you can merge into ``v0.5.0``. If you do not break the API, and you want to release your feature with the next minor release (``v0.4.1``, etc.), you have to merge into ``dev``
* The next minor releases will be directly branched from the ``dev``

**Comment by uvchik** [comment]
And please have a look if everything is fine with 'your' [example](https://github.com/oemof/oemof-examples#oemof-solph-oemof).
