### ISSUE TITLE
There is no built-in function to plot an EnergySystem

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-solph#674]
Since a while, oemof allows the user to create an networkx-graph from an EnergySystem. This is very helpful for visualization, but also for a quick visual sanity check. Until now, the user has to implement a plot function herself. 

We (@Bachibouzouk and @jnnr) think that it would be an improvement to have a plot function that works out of the box, especially for quick checks. If you agree, we will proceed and develop one. It could be part of the oemof.graph module. The API could be like EnergySystem.plot_graph() or something like this.

Potential problems: With large EnergySystems, the plot will probably run into trouble fitting all buses and nodes into one picture. A good graph layout can help to some extent.

**Comment by joroeder** [comment]
I think there is nothing against such a feature, actually, this would be really nice.
Do you need to import an extra library for doing that, which increases the dependencies? For windows, there are sometimes some issues installing pygraphviz …

**Comment by jnnr** [comment]
Having extra dependencies in mind is a good point. The example [transshipment.py](https://github.com/oemof/oemof-examples/blob/master/oemof_examples/oemof.solph/v0.3.x/electrical/transshipment.py) implements a draw_graph() function which seems to only require matplotlib, so it should be possible.

**Comment by uvchik** [comment]
We can always reconsider old decisions, but some time ago we decided that we do not want to have the matplotlib as a requirement of `solph`. The reason is that it is always good to have as less requirements as possible. As `solph` is a model generator people may not expect plotting packages as dependencies and people are free to choose their own plotting environment.

Furthermore the plotting example does need `pygraphviz`. I got reports that it is difficult to install  `pygraphviz` on Windows-OS, which would be an unnecessary burden to install `solph`.

A result of this decision was the oemof-visio repository. It was created to contain all plotting scripts connected to oemof.

**Comment by jnnr** [comment]
The trouble with pygraphviz is a stopper. If there is no way avoiding it, I would refrain from introducing it to solph.

Still, being able to plot the graph easily would be a real improvement, as it is of immediate use for checking and debugging. Maybe we can find a way to avoid any problematic dependency?

**Comment by uvchik** [comment]
If it is for debugging you can use `networkx` to find orphaned nodes etc..

It is already possible to export the graph to an `.graphml`-file and open it with yEd.

For large `EnergySystems` the plot will be totally overloaded and you will not be able to see anything. In yEd it is easier to zoom, sort and group even large systems. The `create_nx_graph` function also allows to remove some nodes and I would recommend to remove global sources.

**Comment by Bachibouzouk** [comment]
I agree that it is nice not to overcrowd the `solph` with visualization packages. One way to tackle this could be to add `matplotlib` to the `extras_require` of the `setup.py` file, so they are only installed if the user run 
```
pip install oemof[viz]
```
Another way could be to add this `visualize-network` ability in the `oemof-visio` package.

I would picture the main use of this ability for beginners who build small `EnergySystems` and could appreciate a vizual feedback of their network (at least I feel that way as an `oemof` beginner). I am not a python beginner and it was not easy to get an out-of-the-box nice visualization of the network, then the one I got had busses drawn as circles and not lines. I personally like the lines to represent the busses on which components are connected ([https://www.researchgate.net/figure/Block-diagram-of-renewable-energy-system-following-refrigerator-80-W-freezer-80-W_fig1_326625533](sketch of busses as lines))

**Comment by jnnr** [comment]
The advantage of the approach using yEd is that you have the option of manually adjusting the plot result starting from a good initial picture, move some components around and quickly get a graph plot that can used in a publication.

**Comment by Bachibouzouk** [comment]
The package [cytoscape](https://cytoscape.org/) is implemented as a [dash component of plotly](https://dash.plot.ly/cytoscape), that could also be an option.

**Comment by p-snft** [comment]
I would really like to see this happen. Windows use of pygraphviz has improved a lot, so this is not a show stopper anymor. However, I generally see visualization in visio.

Side note: There are plans to make an extra package, `oemof-solph` (#639). So, the `oemof` package might have `oemof-solph` as a dependency and `oemof_visio` as an extra.

**Comment by jnnr** [comment]
As a reference: The plot function shown in the documentation of temoa uses pygraphviz and have a clean layout:  https://temoacloud.com/temoaproject/Documentation.html#network-diagrams

**Comment by smartie2076** [comment]
@chrklemm created a somewhat neater plot of energy systems [for the spreadsheet energy system generator](https://git.fh-muenster.de/ck546038/spreadsheet-energy-system-model-generator) [here](https://git.fh-muenster.de/ck546038/spreadsheet-energy-system-model-generator/-/blob/master/program_files/create_graph.py), but it is connected to the input spread sheets.

**Comment by chrklemm** [comment]
@smartie2076 thank you for linking my project. Please let me know if I can help to change my "create_graph" function into a general oemof function.

I attached a picture of an graph created with the "create_graph" function of the [Spreadsheet Energy System Model Generator](https://spreadsheet-energy-system-model-generator.readthedocs.io/en/latest/)

![graph gv](https://user-images.githubusercontent.com/48713015/81819944-406bd900-9530-11ea-8cb9-1513214ea81e.png)

**Comment by nesnoj** [comment]
oemof really lacks a nice visualization and I like the interactive style @chrklemm implemented using plotly. It'd be great to have something similar in oemof-visio.

PS: It might be worth to consider showing derived results from the Analyzer #482 as soon as it's implemented and to access data from the DB result module (wasn't able to find that PR @henhuy).

**Comment by henhuy** [comment]
> access data from the DB result module

This is already merged, see https://github.com/oemof/oemof.db/blob/dev/src/oemof/db/results.py

**Comment by nesnoj** [comment]
Great, wasn't aware of that!

**Comment by uvchik** [comment]
> oemof really lacks a nice visualization and I like the interactive style @chrklemm implemented using plotly. It'd be great to have something similar in oemof-visio.

It is difficult to create a plotting tool for a generic package like oemof-solph. There has been an approach but it did not work out for most systems. For me the `.graphml` export of oemof-solph is the best we have at the moment. It is a good base to go on with WYSIWYG tools like yEd.

But you can convert a oemof-solph (or network) graph to a networkx graph and will find some examples how to plot networkx graphs searching the web. 

You can also find something in the [oemof-examples](https://github.com/oemof/oemof-examples/blob/master/oemof_examples/oemof.solph/v0.3.x/electrical/lopf.py). This is a simple example put can extend the `draw_graph` function in the example with the ideas of @chrklemm.

@Bachibouzouk How far have you got with your approach?

**Comment by Bachibouzouk** [comment]
```python
class ESGraphRenderer:
    def __init__(
        self,
        energy_system=None,
        filepath="network",
        img_format=None,
        legend=True,
        txt_width=10,
        txt_fontsize=10,
        **kwargs
    ):
        """Draw the energy system with Graphviz.

        Parameters
        ----------
        energy_system: `oemof.solph.network.EnergySystem`
            The oemof energy stystem

        filepath: str
            path, where the rendered result shall be saved, if an extension is provided, the format
            will be automatically adapted except if the `img_format` argument is provided
            Default: "network"

        img_format: str
            extension of the available image formats of graphviz (e.g "png", "svg", "pdf", ... )
            Default: "pdf"

        legend: bool
            specify, whether a legend will be added to the graph or not
            Default: False

        txt_width: int
            max number of characters in a line before a line break
            Default: 10

         txt_fontsize: int
            fontsize of the image's text (components labels)
            Default: 10

        Returns
        -------
        None: render the generated dot graph in the filepath

        Notes
        --------
        When new oemof-solph asset types are added to the available types in the MVS, this function needs to be updated, so that it can render the asset in the graph.
        """
        file_name, file_ext = os.path.splitext(filepath)

        if img_format is None:
            if file_ext != "":
                img_format = file_ext.replace(".", "")
            else:
                img_format = "pdf"

        self.dot = graphviz.Digraph(filename=file_name, format=img_format, **kwargs)
        self.txt_width = txt_width
        self.txt_fontsize = str(txt_fontsize)
        self.busses = []

        if legend is True:
            with self.dot.subgraph(name="cluster_1") as c:
                # color of the legend box
                c.attr(color="black")
                # title of the legend box
                c.attr(label="Legends")
                self.add_bus(subgraph=c)
                self.add_sink(subgraph=c)
                self.add_source(subgraph=c)
                self.add_transformer(subgraph=c)
                self.add_storage(subgraph=c)

        # draw a node for each of the network's component. The shape depends on the component's type
        for nd in energy_system.nodes:
            if isinstance(nd, oemof.solph.network.Bus):
                self.add_bus(nd.label)
                # keep the bus reference for drawing edges later
                self.busses.append(nd)
            elif isinstance(nd, oemof.solph.network.Sink):
                self.add_sink(nd.label)
            elif isinstance(nd, oemof.solph.network.Source):
                self.add_source(nd.label)
            elif isinstance(nd, oemof.solph.network.Transformer):
                self.add_transformer(nd.label)
            elif isinstance(nd, oemof.solph.components.GenericStorage):
                self.add_storage(nd.label)
            else:
                logging.warning(
                    "The component {} of type {} is not implemented in the rendering "
                    "function of the energy model network graph drawer. It will be "
                    "rendered as an ellipse".format(nd.label, type(nd))
                )
                self.add_component(nd.label)

        # draw the edges between the nodes based on each bus inputs/outputs
        for bus in self.busses:
            for component in bus.inputs:
                # draw an arrow from the component to the bus
                self.connect(component, bus)
            for component in bus.outputs:
                # draw an arrow from the bus to the component
                self.connect(bus, component)

    def add_bus(self, label="Bus", subgraph=None):
        if subgraph is None:
            dot = self.dot
        else:
            dot = subgraph
        dot.node(
            label,
            shape="rectangle",
            fontsize="10",
            fixedsize="shape",
            width="4.1",
            height="0.3",
            style="filled",
            color="lightgrey",
        )

    def add_sink(self, label="Sink", subgraph=None):
        if subgraph is None:
            dot = self.dot
        else:
            dot = subgraph
        dot.node(
            fixed_width_text(label, char_num=self.txt_width),
            shape="trapezium",
            fontsize=self.txt_fontsize,
        )

    def add_source(self, label="Source", subgraph=None):
        if subgraph is None:
            dot = self.dot
        else:
            dot = subgraph
        dot.node(
            fixed_width_text(label, char_num=self.txt_width),
            shape="invtrapezium",
            fontsize=self.txt_fontsize,
        )

    def add_transformer(self, label="Transformer", subgraph=None):
        if subgraph is None:
            dot = self.dot
        else:
            dot = subgraph
        dot.node(
            fixed_width_text(label, char_num=self.txt_width),
            shape="rectangle",
            fontsize=self.txt_fontsize,
        )

    def add_storage(self, label="Storage", subgraph=None):
        if subgraph is None:
            dot = self.dot
        else:
            dot = subgraph
        dot.node(
            fixed_width_text(label, char_num=self.txt_width),
            shape="rectangle",
            style="rounded",
            fontsize=self.txt_fontsize,
        )

    def add_component(self, label="component", subgraph=None):
        if subgraph is None:
            dot = self.dot
        else:
            dot = subgraph
        dot.node(
            fixed_width_text(label, char_num=self.txt_width),
            fontsize=self.txt_fontsize,
        )

    def connect(self, a, b):
        """Draw an arrow from node a to node b

        Parameters
        ----------
        a: `oemof.solph.network.Node`
            An oemof node (usually a Bus or a Component)

        b: `oemof.solph.network.Node`
            An oemof node (usually a Bus or a Component)
        """
        if not isinstance(a, oemof.solph.network.Bus):
            a = fixed_width_text(a.label, char_num=self.txt_width)
        else:
            a = a.label
        if not isinstance(b, oemof.solph.network.Bus):
            b = fixed_width_text(b.label, char_num=self.txt_width)
        else:
            b = b.label

        self.dot.edge(a, b)

    def view(self, **kwargs):
        """Call the view method of the DiGraph instance"""
        self.dot.view(**kwargs)

    def render(self, **kwargs):
        """Call the render method of the DiGraph instance"""
        self.dot.render(**kwargs)
```

I made it here in a class

**Comment by nailend** [comment]
@SabineHaas might be interesting to plot the energy system graphs

**Comment by Bachibouzouk** [comment]
> @SabineHaas might be interesting to plot the energy system graphs

@SabineHaas  @nailend If it is for `oemof-tabular` I need to update the code for the lastest `oemof-solph` version as I tried recently and it cannot produce a graph anymore

**Comment by nailend** [comment]
> @SabineHaas @nailend If it is for `oemof-tabular` I need to update the code for the lastest `oemof-solph` version as I tried recently and it cannot produce a graph anymore

I also wrote some code to make a graph. Its for a special use case but can easily be used and further developed. I am basically using networkx and graphviz. See [here](https://github.com/oemof/oemof-tabular/blob/88e268b3f0f9e96e1dbde969b2e02e7da637f0a1/tests/mobility_plotting.py#L89-L192)


![bev_fleet](https://github.com/oemof/oemof-solph/assets/51374526/5969530c-9fa3-4916-a3bd-71bc662704e0)

**Comment by p-snft** [comment]
Just for completeness: The cheapest version to create a graph is as easy as
```Python
import networkx
from oemof.network.graph import create_nx_graph
graph = create_nx_graph(energy_system)
networkx.draw(graph, with_labels=True, font_size=8)
```

It's not styled but it can help already.
