### ISSUE TITLE
How to avoid contradictory values between 'timeincrement' and 'timeindex'

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof-solph#678]
With commit b18ad23210 it is possible to define a `timeindex` and a `timeincrement`in the energy system. This makes it possible to use nonequidistant time steps (see #668).

Now two issues occurred:

1. As @p-snft mentioned it is now possible that the `timeindex` and the `timeincrement` are contradictory.

2. If people define a `timeincrement` a `timeindex` is only used to define the number of steps, therefore, it might more convenient to define something like `number_of_steps` and not a full `timeindex`.

A possible solution would be that people can either pass a `timeindex` or `timeincrement` and `number_of_steps`. The timeindex works only for equidistant time steps.

**Comment by uvchik** [comment]
We may do some changes without an API break. For the rest we have to wait until `v0.5.0`.

**Comment by p-snft** [comment]
Fixed in dev.
