### ISSUE TITLE
Missing test for non-equidistant timeindex

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-solph#684]
The new feature (added in #668) is not tested anywhere yet. Please add one ore more tests.

@c-koehl, @oemof/oemof-solph

**Comment by c-koehl** [comment]
What kind of tests are you thinking of? You can find my tests [here](https://github.com/c-koehl/oemof/blob/ac76b7346e2f78cde658bce0bc1ef68b3d1683f2/tests/test_models.py#L47).

**Comment by jnnr** [comment]
Hey there, sorry for the late reply. You are right, there are already some tests, and they are also merged together with PR #668. It seems like I have overlooked them. Sorry, my bad! 

Looking at the tests i noticed that despite them being in test_models, they only test the function calculate_timeincrement of oemof.tools.helpers. Another test that actually tests how a model with a nonequidistant timeindex is build (and comparing lp files) could be added? I have no complete overview over all kinds of tests we have in oemof, so someone else might have a better idea :)

**Comment by c-koehl** [comment]
I created a pr for this issue (see above). Is it sufficient?

**Comment by uvchik** [comment]
The PR is move to the next milestone, so I will move this issue, too.

**Comment by p-snft** [comment]
There is one now.
