### ISSUE TITLE
'Module contents' in apidocs are empty

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-solph#691]
In the apidocs, for each module there is a section "Module contents" at the very bottom. I am not sure what it is intended for. In the build, there is nothing displayed, just the headline. Does anyone have an idea what this is for? Shall we fix it or remove it?

For example here:

https://oemof.readthedocs.io/en/stable/api/oemof.tools.html#module-oemof.tools

**Comment by joroeder** [comment]
If ther is nowhere content, we should remove it, in my opinion

**Comment by fwitte** [comment]
I think, it is necessary to include the module contents even if it is empty as referring via 
```
:py:mod:`package.submodule`
```
links to that anchor. I'm not fully sure, though.

**Comment by jnnr** [comment]
The problem does not seem to be prevailing.
