### ISSUE TITLE
Scalars stored in sequences in single timestep optimisation

### ISSUE THREAD

**Issue by joroeder** [oemof/oemof-solph#693]
If an optimisation with one timestep is performed, the outputlib stores the scalars of the results in the dict of the sequences.

So, I guess in `outputlib.processing.results(om)`, the following condition must be somehow adapted:

[https://github.com/oemof/oemof/blob/8640ea712da8db4227979d06ed12aedfab9c7c66/oemof/outputlib/processing.py#L131](https://github.com/oemof/oemof/blob/8640ea712da8db4227979d06ed12aedfab9c7c66/oemof/outputlib/processing.py#L131)

If there is a scalar, at 2 and more timesteps, there will be a `NaN` at the second timestep at all scalars without the need of knowing the attributes name. This must be replaced. Any ideas?

**Comment by uvchik** [comment]
I am not sure if this is still valid. I tried to reproduce it but maybe I did not got the idea.

 @joroeder Could you check and add an example or better a failing test?

**Comment by p-snft** [comment]
I will move this to v0.5.1. If it's not triaged when that version is about to be released, I'd consider this bug not existing.
