### ISSUE TITLE
Installing `oemof.thermal` creates "network.py"

### ISSUE THREAD

**Issue by Fernando3161** [oemof/oemof-solph#708]
When installing oemof.thermal a network.py file is created, which confuses the import with the oemof.network package when importing.

**Comment by jnnr** [comment]
Can you tell us a bit more so we can reproduce this? Where does this network.py appear exactly? Thanks!

We are planning the 0.0.3 release for oemof.thermal, so this is a good opportunity to fix this. @oemof/oemof-heat

**Comment by Fernando3161** [comment]
Sure.
So, I installed oemof.solph (using pip), which creates the oemof/network directory.
When installed oemof.thermal (using pip), the pile oemof/network.py is created 
(Not 100% sure, but I think that using pip install oemof.thermal creates also an older instance of oemof 0.3 that creates the oemof/network.py).

I fixed it by first removing all of oemof components, then installing oemof.solph using pip, and by NOT installing oemof.thermal using pip, but rather by downloading the oemof.thermal repository folder (zip) and copying the /thermal folder in the oemof directory.

**Comment by jnnr** [comment]
Hey, thanks. It is very probable that this is because the current release of oemof.thermal relies on the old oemof.solph v0.3. We are about to release an updated version of oemof.thermal these weeks, so we should test if that fixes your problem.

**Comment by p-snft** [comment]
`oemof.thermal` now depends on `oemof.solph`. This should fix the problem.
