### ISSUE TITLE
Missing lines in solph.processing.results()

### ISSUE THREAD

**Issue by AntonellaConsolinno** [oemof/oemof-solph#714]
Hey,

I'am not quite sure if it is a really bug or if you had some intentions by removing the lines in the oemof.solph verison 0.4.

Following lines are "missing" at the results() function of oeomf.solph.processing.results():

`df_dict[k].columns.name = k[0].label`
 `if "flow" in  df_dict[k].columns:
     df_dict[k] = df_dict[k].rename(columns={"flow": k[1].label})`

Best regards,
Antonella

**Comment by uvchik** [comment]
Did you find the lines above in a previous version and they are gone now?
In which version did you find it?
What in the results is different than before?

**Comment by AntonellaConsolinno** [comment]
Yes the lines have been in the previous version (I'm not quite sure but it could be version v0.3.1). 

The function was defined as:

```
 def results(om):
  
    df = create_dataframe(om)

    # create a dict of dataframes keyed by oemof tuples
    df_dict = {k if len(k) > 1 else (k[0], None):
               v[['timestep', 'variable_name', 'value']]
               for k, v in df.groupby('oemof_tuple')}
    # create final result dictionary by splitting up the dataframes in the
    # dataframe dict into a series for scalar data and dataframe for sequences
    result = {}
    for k in df_dict:
        df_dict[k].set_index('timestep', inplace=True)
        df_dict[k] = df_dict[k].pivot(columns='variable_name', values='value')
        try:
            df_dict[k].index = om.es.timeindex
            df_dict[k].columns.name = k[0].label
            if "flow" in df_dict[k].columns:
                df_dict[k] = df_dict[k].rename(columns={"flow": k[1].label})
        except ValueError as e:
    ...
```


In the new version (oemof v.0.4.1) the lines
```
df_dict[k].columns.name = k[0].label
if "flow" in df_dict[k].columns:
     df_dict[k] = df_dict[k].rename(columns={"flow": k[1].label})

```
 are missing.

So if you use the function then the busses are all called "flow" and so you do not get the label of the bus as name. Furthermore you are not able to view the labels of the components by calling columns.names. Before the naming was very useful. I used this for an automatic reporting and with the new oemof I got some problems.

**Comment by uvchik** [comment]
I will try to find out what happened there. Could you write a minimal example that works with the old version but does not work with v0.4. That would help me to fix your issue.

**Comment by AntonellaConsolinno** [comment]
I took the chp-example from oemof-examples.

```
# -*- coding: utf-8 -*-

"""
General description
-------------------
Example that illustrates how to use custom component `GenericCHP` can be used.
In this case it is used to model a motoric chp.

Installation requirements
-------------------------
This example requires the version v0.3.x of oemof. Install by:

    pip install 'oemof.solph>=0.4,<0.5'

"""

__copyright__ = "oemof developer group"
__license__ = "GPLv3"

import os
import pandas as pd
from oemof import solph
from oemof.network.network import Node

try:
    import matplotlib.pyplot as plt
except ImportError:
    plt = None



# select periods
periods = 3

# create an energy system
idx = pd.date_range("1/1/2017", periods=periods, freq="H")
es = solph.EnergySystem(timeindex=idx)
Node.registry = es

# resources
bgas = solph.Bus(label="bgas")

rgas = solph.Source(label="rgas", outputs={bgas: solph.Flow()})

# heat
bth = solph.Bus(label="bth")

# dummy source at high costs that serves the residual load
source_th = solph.Source(
    label="source_th", outputs={bth: solph.Flow(variable_costs=1000)}
)


demand_th = solph.Sink(
    label="demand_th",
    inputs={bth: solph.Flow(fix=[5 for p in range(0,periods)], nominal_value=200)},
)

# power
bel = solph.Bus(label="bel")

demand_el = solph.Sink(
    label="demand_el",
    inputs={bel: solph.Flow(variable_costs=[3 for p in range(0,periods)])},
)

# motoric chp
mchp = solph.components.GenericCHP(
    label="motoric_chp",
    fuel_input={
        bgas: solph.Flow(
            H_L_FG_share_max=[0.18 for p in range(0, periods)],
            H_L_FG_share_min=[0.41 for p in range(0, periods)],
        )
    },
    electrical_output={
        bel: solph.Flow(
            P_max_woDH=[200 for p in range(0, periods)],
            P_min_woDH=[100 for p in range(0, periods)],
            Eta_el_max_woDH=[0.44 for p in range(0, periods)],
            Eta_el_min_woDH=[0.40 for p in range(0, periods)],
        )
    },
    heat_output={bth: solph.Flow(Q_CW_min=[0 for p in range(0, periods)])},
    Beta=[0 for p in range(0, periods)],
    fixed_costs=0,
    back_pressure=False,
)

# create an optimization problem and solve it
om = solph.Model(es)

# debugging
# om.write('generic_chp.lp', io_options={'symbolic_solver_labels': True})

# solve model
om.solve(solver="cbc", solve_kwargs={"tee": True})
```
No looking at the results within v0.4 you get not the names of the components and the flows. Instead you the universal name 'variable_name' and every flow is names flow instead of the label.
```
# create result object
results = solph.processing.results(om)
results = solph.views.convert_keys_to_strings(results, keep_none_type=True)

nodes = [x for x in results.keys() if x[1] is None]
# for example first node
node = nodes[0]
sequence = results[node]["sequences"]

print(sequence.columns.name)
# 'variable_name'

flows = [x for x in results.keys() if x[1] is not None]

#for example first flow
flow = flows[0]


print(results[flow]["sequences"])


"""
variable_name         flow
2017-01-01 00:00:00  200.0
2017-01-01 01:00:00  200.0
2017-01-01 02:00:00  200.0

"""


```

In the version before I got the names


```
# create result object
results = solph.processing.results(om)
results = solph.views.convert_keys_to_strings(results, keep_none_type=True)

nodes = [x for x in results.keys() if x[1] is None]
node = nodes[0]
sequence = results[node]["sequences"]

print(sequence.columns.name)
# 'motoric_chp'


flows = [x for x in results.keys() if x[1] is not None]

#for example first flow
flow = flows[0]
results[flow]["sequences"]

"""
results[flow]['sequences']
bel                  demand_el
2017-01-01 00:00:00      200.0
2017-01-01 01:00:00      200.0
2017-01-01 02:00:00      200.0
""

```

Within my local version of the new oemof (v0.4) I have already added the lines within the processing.results() method and it works as it should work. I just wanted to tell you, that the lines are missing, so you can perhaps add them again to get the functionality back.


```

**Comment by uvchik** [comment]
Thank you for the details. I will check and try to fix it.

**Comment by uvchik** [comment]
As I see it, this line was never part of an official release. You may have found it in a developer branch or a fork.

It looks like a hack that might be helpful in some situations but it breaks the overall structure.

The key of a Flow in the results dictionary has the form [source, target], while the related value contains two more keys. One for the `sequences` and one for the `scalars`. The related value to the `sequences` key is a pandas.DataFrame which contains all sequences. In this pandas DataFrame the name of the columns is the name of the variable. In your case the name of the variable is `flow`. 

In pandas you can name your columns to explain what they are about. For example if you have a table with information about cities with values like number of habitants, area,... in the index and the name of the city in the columns the attribute `dataframe.columns.name` could be "name of the city" because you find the name of the city in the columns.

In our case the attribute is `variable name` because you can find the name of the variable in the columns. It might be confusing because in most cases there is only one column but not all the time. What you did is to use the name of the columns attribute to name it with the source of the flow and the first column with the target of the flow which will be totally confusing if you have a second column with the variable name as the name of the column.

If you have more than one column the name of the column must be the name of the variable to identify the results. The name of the flow is already in the key! There is no need to add the name in the value, too. And it is confusing if you misuse existing attributes for that.

**Comment by AntonellaConsolinno** [comment]
Thank you so much for checking my issu and for the detailed explanation! I'am sorry, that I did not realized that the code was within a development version.
