### ISSUE TITLE
Mainline "link"

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof-solph#723]
For quite some time, there has been a "Link" component in "custom" that is meant for lossy transport of electricity between two buses (typically locations). With #720, the component has been enhanced to allow exclusive Flow in either one or the other direction.

Next, I want to mainline the component. The following is missing:

* [x] Documentation
* [x] Tests

It turned out that it might be helpful to have two approaches for different purposes:
1. `Binary`: This one has a binary constraint. The constraint `limit_active_flow_count` might be used, but a component might be easier.
2. `Signed`: This one would solve faster but allows flows at both sides. A `SignedFlow` might be used instead of the `Link`.

**Comment by p-snft** [comment]
The documentation should carefuly explain why and under which conditions the link works. (Including the formulas.)

**Comment by jnnr** [comment]
#754 Introduced two new constraints that force a direction to the links. This introduces a binary variable that represents the direction. This can lead to significant extra computation time. In some applications, this may be justified and useful. In others, it may be not desired. To avoid loop flows, small `variable_cost` can be set instead.

To conclude: The 2 extra equaions should be optional, e.g with a flag `unidirectional=True/False`.

Any ideas how to implement this in a clean way?

**Comment by p-snft** [comment]
In https://github.com/oemof/oemof-solph/pull/838, @henhuy added the flag `limit_direction`. I agreed to not slow things down with fixing tabular and as the component is still experimental. Actually, I like `unidirectional` better.

**Comment by henhuy** [comment]
Hey @minhki95,

this is exactly the same error, which led to implementation of #838 . With this implementation you should be able to add parameter `limit_direction=False` to your Link component. But maybe your model should work also with current setting?! not sure...

**Comment by minhki95** [comment]
Thanks @henhuy it worked! So, what exactly is the reason that the run fails, if `limit_direction=True` ?
Or is it just in my case that it does? As far as I have understood if `limit_direction=False` does not add the 1st and 2nd inflow constraint to the program right?

**Comment by p-snft** [comment]
> I saw that the Link component as it is right now is not working, which is also confirmed by an example that was working in version v0.4.4. I would be glad to help out in whatever capacity it is possible.

So, it worked in v0.4.4 but it is currently not working? I had a quick look and I assume that the problem is caused by the updated Pyomo version we use for v0.5. As there are no tests for the Link, yet, nobody noticed that it currently depends on the old version.

**Comment by jnnr** [comment]
Link is useful, e.g. in oemof.tabular. Therefore, it should be part of the established components.

What has to be provided to do so?

- good docstrings
- tests
- working example
- higher subjective code quality requirements
- fix Link in `limit_direction=True` mode
- ...?
