### ISSUE TITLE
Rename Transformer

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof-solph#728]
When people hear "transformer", they think of electrical devices. However, the `GenericTransformer` is neither meant to be (only) electrical nor bidirectional (as electrical transformers typically are). Thus, I got the suggestion (thx to @psychon) to rename it to `GenericConverter`. The term is more general and does not imply that back-conversion is possible.

**Comment by psychon** [comment]
I like this idea, but also do not have much problems with "transformer".

**Comment by Fernando3161** [comment]
Coming from a pure engineering background and hearing "transformer" in the first examples led me to a serious confusion. I would strongly advice to rename this.

**Comment by p-snft** [comment]
We should make a decision in a plenum session at https://github.com/oemof/oemof/issues/96.
