### ISSUE TITLE
How can typos be caught?

### ISSUE THREAD

**Issue by psychon** [oemof/oemof-solph#729]
This started with my PR #727. Before implementing another suggestion, I feel like there should first be a rough consensus about what the solution should be.

First, the problem: People make typos. When someone writes `Flow(variable_cost=42)`, the missing s (did you spot it?) is silently ignored and one gets a wrong result. Thus, the suggestion is to catch these typos. Somehow.

The problem is complicated by people wanting to be able to add arbitrary properties to objects. So, `print(Flow(my_cool_property=42).my_cool_property)` should produce `42`.

So, here are some random thoughts about possible aspects of a solution:

- When should typos be checked?
  - At each single object construction
  - When the `Model` instance is constructured from the energy system
  - When solving a model
  - With an explicit call to `check_for_unknown_properties()`
- How should the checking work?
  - Instead of having `Flow.__init__(**kwargs):`, only the known properties are available as named arguments. New properties could be added via a special `custom_properties` argument. (Of course, the name for this argument is open for bike-shedding)
  - There could be an internal list of known properties. Everything not known is "bad". Users could add own properties.
    - ...in a global list of known properties
    - ...as an argument somewhere somehow to the check itself
- What should the result of the check be?
  - Exception
  - SuspiciousUsageWarning
  - a list/dict/... of `$SOMETHING` that is returned to the caller
  - Nothing (the current state of things: no typo checks done)

Uhm... that's it. These are all the possibilities I could come up with. Feel free to think about this and add more options. If you have the powers to do so, feel free to edit this comment so that there is "a single list of everything".

No idea how the usual oemof decision making works. Depending on mood, time, and the phase of the moon, I might or might not be able to send a PR for whatever version is preferred.

**Comment by fwitte** [comment]
I have a similar "issue" over at https://github.com/oemof/tespy:

For most classes I have `**kwargs` in the `__init__` or `set_attr` methods, but do only allow keywords which are specified in an attribute/a method of the respective class.
- I like this method for the reason, that the setter can be the same for every subclass of the parent class `component` etc..
- But dislike it at the same time for the reason, that the lists of available parameters is stored somewhere else and not automatically available when creating an object.
This "concept" emerged in my very early stages of programming, therefore I would be more than happy, if someone has a good idea/concept to implement this "correctly". On top of that, the code of the oemof libraries could somewhat converge a little bit (e.g. regarding https://github.com/oemof/tespy/issues/219).

**Comment by uvchik** [comment]
This problem has a lot of aspects, so it might be good topic for an online-session at the [next meeting in December](https://github.com/oemof/oemof/issues/80). :smile:

**Comment by p-snft** [comment]
I already suggested an according session: https://github.com/oemof/oemof/wiki/Meeting-December-2020-(online)#function-signatures

**Comment by p-snft** [comment]
The decision has been made: Arguments will be explicit. We aim to do the change for v0.5.0.

**Comment by lensum** [comment]
Maybe I'm missing something here, but does making arguments explicit actually catch typos? It might prevent some (thanks to the suggestions and autocomplete functions) but it does not really catch them, does it? I just spend a good amount of time on fixing a model where I (embarrassingly enough) missed the "s" at the end of `variable_costs`. The only hint was that `pyomo` told me that the objective was constant.
I would've liked something like a SuspiciousUsageWarning that gives me a list of attributes that are passed to the object but not actually used. 
One way I could think of doing that, would be to use `kwargs.pop(variable_costs)` instead of `kwargs.get(variable_costs)` by default. Afterwards, a SuspiciousUsageWarning could show all "non-popped" kwargs. This would eliminate the need to have some kind of list of all the kwargs that are actually being used...

**Comment by p-snft** [comment]
Typos are common and missing the 's' in `variable_costs` is a good example. Making the argument explicit helps if you disallow unknown arguments.

I like the alternative suggestion of using `kwargs.pop(variable_costs)`. However, currently all arguments are passed to all parent classes before they are interpreted. Thus, bookkeeping the non-popped args is not a trivial thing.

**Comment by jokochems** [comment]
Can be closed in favor of #733 and everything related to it, can't it?

**Comment by p-snft** [comment]
This is a bit of miscommunication. This issue will be solved by #877.
