### ISSUE TITLE
Solph Logo

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof-solph#745]
The idea came up to create a solph logo derived from the oemof logo.

@oemof/oemof-solph  / @oemof-developer What do you think?

**Comment by uvchik** [comment]
First sketch.

![test_logo_solph](https://user-images.githubusercontent.com/4760584/107929067-6cadfd80-6f79-11eb-9055-9269f2f76e15.png)

**Comment by p-snft** [comment]
I like the style but don't get what the braces stand for. Can you tell me?

**Comment by fwitte** [comment]
If you want to go in line with the oemof logo, o e mo f should be highlighted in the second line, I feel. Like here: https://github.com/oemof/oemof/blob/master/logo/logo_oemof_big.svg

**Comment by uvchik** [comment]
> If you want to go in line with the oemof logo, o e mo f should be highlighted in the second line, I feel. Like here: https://github.com/oemof/oemof/blob/master/logo/logo_oemof_big.svg

We could do that but in the oemof logo the bold letters result in oemof but in our case the bold letters do not result in solph, so I decided to leave all letters normal. But I do not have a strong opinion on that.



> I like the style but don't get what the braces stand for. Can you tell me?

The constraint set is often in one or two brackets. But one bracket does not look good. It is difficult to find an abstract idea of linear optimisation and I am open for other ideas.

![image](https://user-images.githubusercontent.com/4760584/108482140-62517380-7299-11eb-8cff-184b2f98700e.png)

![image](https://user-images.githubusercontent.com/4760584/108481985-2dddb780-7299-11eb-8390-289255edbdda.png)

**Comment by p-snft** [comment]
It's programmer graphics, but "linear optimisation" for me looks something like this:
![grafik](https://user-images.githubusercontent.com/4871848/108488471-b744b800-72a0-11eb-88d3-6a7559f9a626.png)

**Comment by uvchik** [comment]
BTW: The basic svg-files are here: https://github.com/oemof/oemof-solph/tree/docs/improve-readme/docs/_logo

**Comment by uvchik** [comment]
Inspired by @p-snft I created the following idea:

![logo_oemof_solph_big_editable_font_alt_uk1](https://user-images.githubusercontent.com/4760584/108556006-9f981e80-72f6-11eb-91b7-e138c2434567.png)

**Comment by p-snft** [comment]
I like the his suggestion but I always try to have an overall impression that overall the lines go up. (As this is seen as positive in western cultures.)

**Comment by jokochems** [comment]
I like the idea of a separate logo (for each package?) and your drafts.

**Comment by c-moeller** [comment]
I also like the idea. Looks good :+1: I would suggest, while adjusting the logos, to also have a look at the end of both lines which are not in line. This is something which annoys me also in the original oemof logo since we have it :smile:

**Comment by uvchik** [comment]
![logo_oemof_solph_big_editable_font_green](https://user-images.githubusercontent.com/4760584/117715082-1945f700-b1d8-11eb-8dc7-256eb0dca2bc.png)

**Comment by uvchik** [comment]
![logo_oemof_solph_big_editable_font_blue](https://user-images.githubusercontent.com/4760584/117715117-22cf5f00-b1d8-11eb-9a6c-f11faebddc7a.png)

**Comment by uvchik** [comment]
I think we should bring this to an end and start a first voting. You can vote for more than one sketch. Afterwards there are still some small changes possible e.g. "I like the blue sketch but the line width should be 6 instead of 8".

1. [Logo green with {s}](https://user-images.githubusercontent.com/4760584/107929067-6cadfd80-6f79-11eb-9055-9269f2f76e15.png)
2. [Logo green with arrow](https://user-images.githubusercontent.com/4871848/108488471-b744b800-72a0-11eb-88d3-6a7559f9a626.png)
3. [Logo green line down](https://user-images.githubusercontent.com/4760584/108556006-9f981e80-72f6-11eb-91b7-e138c2434567.png)
4. [Logo green line up](https://user-images.githubusercontent.com/4871848/108590274-d60b8300-7362-11eb-9241-216a30106a34.png)
5. [Logo green line up thick](https://user-images.githubusercontent.com/4760584/117715881-2c0cfb80-b1d9-11eb-999b-2cf39a018938.png)
6. [Logo blue](https://user-images.githubusercontent.com/4760584/117715910-34fdcd00-b1d9-11eb-83c2-14b1c5c1be81.png)

You can vote [HERE](https://dudle.inf.tu-dresden.de/nZjsHucRjA/):exclamation:

**Comment by uvchik** [comment]
The winner is the blue logo.

I created the 3 versions of the oemof logo. I think we should keep the general idea but if you have constructive criticism please go ahead. Please contact me if you need the svg-files.

### Full logo

![logo_oemof_solph_big_editable_font_blue](https://user-images.githubusercontent.com/4760584/120376296-011b5080-c31c-11eb-9022-13852314cee1.png)

--------------------------------------------------------------------------------------
### Mid-size logo
![logo_oemof_solph_mid_editable_font_blue](https://user-images.githubusercontent.com/4760584/120376077-bd284b80-c31b-11eb-95b8-9bb60254b145.png)

--------------------------------------------------------------------------------------
### Small Logo
![logo_oemof_solph_sizes_editable_font_blue](https://user-images.githubusercontent.com/4760584/120376133-ca453a80-c31b-11eb-8eaa-774ffb1bad58.png)

**Comment by p-snft** [comment]
I consider this done and will close the issue.
