### ISSUE TITLE
UserWarning if summed_max/min without nominal_value is given

### ISSUE THREAD

**Issue by joroeder** [oemof/oemof-solph#755]
If somebody wants to use the `summed_max` (or `summed_min`) contraint for flows, a `nominal_value` must be given. (In the case that it is not an investment flow.)

If only the `summed_max` attribute is given, it is ignored (because value * inf = inf).

So, raising a Warning could help to identify errors in your model setup.

What do you think?

**Comment by p-snft** [comment]
I'd suggest to use `assert math.isfinite(nominal_value)` for this purpose.

**Comment by jokochems** [comment]
Since the default values of `summed_min`, `summed_max` and `nominal_value` are not given, i.e. `None`, I see no need to use the assert statement to check whether nominal value is finite. Instead, we can just check whether it is set, i.e. other than None.

**Comment by jokochems** [comment]
I think this is deprecated / already addressed, see #819. Thus, I think it can be closed.
