### ISSUE TITLE
Time step of "initial_storage_level"

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof-solph#758]
At the moment, "initial_storage_level" signifies the storage level before the first time step. I's suggest to change that to the 1st time step, as this would simplify formulating the constraints.

(Is there any reason to stick to the current definition?)

**Comment by jokochems** [comment]
Hi @p-snft,

I don't know the history, but I always found that very confusing as well and wondered why it had been implemented that way in the first place. Thanks for bringing it up.

**Comment by p-snft** [comment]
By now, I have probably found a reason to have it the current way: It might save one constraint per storage.

**Comment by uvchik** [comment]
If you use the `initial_storage_state` to the first time step you need a `n+1` time step to store the storage state at the end.

I recently discussed that topic with some other users. They suggested to distinguish between state variables and interval variables. For an hourly year we would have 8760 intervals and 8761 states. If we use a datetime index the state variables will be quite clear. For the interval variables we have to make clear if they right-stamped or left-stamped.

So in future we would have to pass a datetime index with n+1 values which also makes it also possible to get the intervals from the datetime index. At the moment assume that the last interval is the same as all the others but this is not possible for non-equidistant time increments.

**Comment by jokochems** [comment]
We had a discussion on this and the difference between time stamps (points in time) and time intervals (time spans) on the dev meeting https://github.com/oemof/oemof/issues/96. So when you simulate a year with 8,760 hours in hourly frequency, you actually have 8,761 values for the storage level when you count the initial one.

@uvchik will provide a suggestion on how to deal with that.

But I tink, for the solution, we have to be aware that the `initial_storage_level` defined so far will be active for the hour **before** the start of the simulation, so the timestep -1 which is not contained within the models' TIMESTEPS (as @p-snft mentioned when creating this issue). I think this was not 100% made clear in our discussion on the dev meeting. But anyways, it should be very clearly documented in the best case using some sort of timeline visualization in the docs.

**Comment by jokochems** [comment]
I think, #811 will resolve this, won't it?

**Comment by p-snft** [comment]
Done.
