### ISSUE TITLE
wrong file for v0.4.2 changelog?

### ISSUE THREAD

**Issue by BurningTrapezoid** [oemof/oemof-solph#762]
In the [changelog on readthedocs](https://oemof-solph.readthedocs.io/en/latest/changelog.html) (latest) the description for the v0.4.2 release doesn't seem right, the text looks more like a draft for the v0.4.3 release.

(but in [stable](https://oemof-solph.readthedocs.io/en/stable/changelog.html) everything seems correct)

**Comment by p-snft** [comment]
Background: v0.4.2 is an emergency hotfix, as many installations pulled a version of Pyomo that was really slow when working with oemof.solph. Thus, it contained changes that were not in the dev branch.
