### ISSUE TITLE
`min` and `max` attributes are not applicable for standard flows

### ISSUE THREAD

**Issue by jokochems** [oemof/oemof-solph#776]
Hi there,

I always though that the `min` and `max` attributes of a Flow can be used to limit _any kind_ of Flow in an energysystem, as can be supposed from the documentation in the `network/flow.py` module:
```    
    max : numeric (iterable or scalar), :math:`f_{max}`
        Normed maximum value of the flow. The flow absolute maximum will be
        calculated by multiplying :attr:`nominal_value` with :attr:`max`
```

It turns out, that these values are only used for InvestmentFlows and NonConvexFlows, but not for standard flows from `blocks/flow.py`. Of course, allowing for arbitrary keyword arguments does not lead to raising a warning or an error for standard flows.

Is there any special reason for it being not implemented for standard flows or should we just add it? <br>The constraints themselves would be fairly simple, i.e. something like
* m.flow[i, o, t] <= m.flows[i, o].max[t] * m.flows[i, o].nominal_value
* m.flow[i, o, t] >= m.flows[i, o].min[t] * m.flows[i, o].nominal_value

**Comment by simnh** [comment]
Hey, 

that's not quite correct. the min / max are used here: https://github.com/oemof/oemof-solph/blob/d7ca5aa440d4f8c0f88e464eed3678f6d08e1d14/src/oemof/solph/models.py#L336-L360

We do not build constraints, but set bounds for the variables directly. Might not be the best, as you would think to find the constraints somewhere else and not in models.

Of course, we could restructure the source code but that would be another issue I guess. :-)

**Comment by jokochems** [comment]
Ah thanks, I must have overlooked that! Then I'll close this one.
To be honest, I would have been very surprised if that wasn't taken care of appropriately.
