### ISSUE TITLE
How to consider future demand growth and price changes while optimizing using Solph library?

### ISSUE THREAD

**Issue by sanketpuranik** [oemof/oemof-solph#792]

**Comment by p-snft** [comment]
This is less of a software issue. Thus, it might make sense to discuss it at https://forum.openmod.org/tag/oemof.

**Comment by jokochems** [comment]
> This is less of a software issue. Thus, it might make sense to discuss it at https://forum.openmod.org/tag/oemof.

I agree. I think it is a matter of (exogenously provided) input data.

**Comment by sanketpuranik** [comment]
Thanks, i shall discuss it in the shared forum.
