### ISSUE TITLE
Multiperiod modeling should be supported

### ISSUE THREAD

**Issue by jokochems** [oemof/oemof-solph#793]
This relates to ongoing work in #750 (now #810). I just noticed that a dedicated issue was missing.

This also resolves related outdated pull requests:
#352
#342

The draft pull request in #750 in principle is functional. I've currently started the process of re-aligning it with the existing solph architecture instead of creating a parallel one. After carefully rethinking it, in my view this is the only approach that makes sense in terms of maintainability and re-usability.

**Comment by jokochems** [comment]
Could someone please link it with #750? Seems I don't have the rights to do so?

**Comment by p-snft** [comment]
> Could someone please link it with #750? Seems I don't have the rights to do so?

It's linked, isn't it?

**Comment by jokochems** [comment]
> > Could someone please link it with #750? Seems I don't have the rights to do so?
> 
> It's linked, isn't it?

I meant to add a Linked pull request for the Issue or vice versa. 
In my other repositories, GitHub offers me the possibility to do so in the control bar on the right hand side. The advantage is that linked issues will be autoclosed once the pull request is merged. So you don't have to do that manually (which you might forgot).

**Comment by jokochems** [comment]
Here's a summary of the discussion at the dev meeting https://github.com/oemof/oemof/issues/96:
* The current approach (see #750) introduces a `multi_period` attribute for the energysystem
  * When this attribute is set to True, different objective values (including discounting to account for different periods) are used.
  * Furthermore, the models' flow variable receives a further index p for the models' new PERIODS set.
  * Basically, in all constraint formulations where a flow variable is referenced, the flow's index is adjusted accordingly.
* I'll resume with the integration of this feature into solph itself. - That is, I won't go for the original idea to create a parallel structure with a lot of code duplication and bad maintainability.
* I'll update the feature to `v0.5.0`. Currently, it is still based on `dev`. For this purpose, I'll probably close the current PR #750 and open a new clean pull request from my fork.
* I'll introduce a case distinction to keep the current results processing as is. This way, this opens the possibility to carefully test the new functionality.
* Remaining TODOs - besides the restructuring - are the proper mapping of periods and unit's lifetimes as well as handling the `initial_storage_level` for the `GenericStorageInvestmentBlock`.
* Of course, I'll write / adjust the tests for this new feature.
* Introducing the new feature could be somewhat like make it a "hidden feature", i.e. keep it under the hood and not prominently advertise it and then open the possibility to carefully test it until it is a full blown feature.

Thanks a lot @oemof-developer for the fruitful discussion! I'm looking forward to getting this one done.

**Comment by jokochems** [comment]
Here's a heads up:
* There is a functioning an experimental version of the multi-period feature available here: https://github.com/oemof/oemof-solph/tree/features/multi-period. Feel free to use and share your experience and opinions.
* There is a dedicated open PR to integrate it into the code basis: #828. Here we can discuss feedback and any changes desired before making it available in a release.
