### ISSUE TITLE
Linting CI should be updated or replaced

### ISSUE THREAD

**Issue by jokochems** [oemof/oemof-solph#804]
The used linting CI for black does not work for Pull Requests issued from forks. (It does not have permissions.)
Maybe it should be updated or replaced to allow so.

**Comment by p-snft** [comment]
Is it even possible to have CI that can just checkout stuff from external repositories?

**Comment by jokochems** [comment]
I don't think the problem still persists, does it? At least for me, I don't get any failing black tests anymore when trying to merge stuff from my fork. I'll therefore close this one. Feel free to reopen if needed.
