### ISSUE TITLE
Flow's argument"fix" is silently ignored when no nominal_value is given

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof-solph#818]
**Describe the bug**
Flow's argument "fix" is silently ignored when no nominal_value is given.

**Current behaviour**
```Python
solph.flows.Flow(fix=0.5)
```
leads to a flow with a non-fixed value without any feedback given.

**Expected behaviour**
As there is no `nominal_value` given, the Flow cannot be fixed. Thus, an error should be thrown.

**Comment by p-snft** [comment]
The problem is also present in the doc strings, so it's not unlikely, people will fall into that trap:

https://github.com/oemof/oemof-solph/blob/060c70f8d556f1e28268dc53d664387359a0d2ea/src/oemof/solph/flows/_flow.py#L119

**Comment by lensum** [comment]
Just wondering: what is the rationale behind the usage of `nominal_value`?
In my use-cases I usually have a time-series that is in absolute values which I use like this:
```
ts =[4, 8, 15, 16, 23, 42] 
fix=ts,
nominal_value=1
```
If I'd stick to the convention of the flows, I'd have to change it to something like this:
```
ts = [4, 8, 15, 16, 23, 42]
fix = ts/max(ts)
nominal_value=max(ts)
```
But I see no benefit in these (tiny) extra calculations. What am I missing here? Or is the `nominal_value` just a convenience? It seems to cause some trouble (referring to this issue as well as https://github.com/oemof/oemof-solph/issues/755). So why not get rid of it in the next version change?

I'm not trying to provoke here, I just wondered about this for quite some time now.

**Comment by p-snft** [comment]
It is perfectly fine to do as you do in your first snippet. Actually, first I also thought that it might simplify things if just the product of `value` (of fix) and `nominal_value` is used. However, imagine optimising e.g. the size of a PV installation. There you would give a time series for the production and it would be scaled automatically depending on the investment.
