### ISSUE TITLE
No executable found for solver 'cbc'

### ISSUE THREAD

**Issue by Afraz85** [oemof/oemof-solph#831]
Hi,
I am trying to install cbc with following commands:
 brew tap coin-or-tools/coinor
brew install coin-or-tools/coinor/cbc
But I am unable to configure it. When I write cbc on my Terminal I get following:
_dyld[63849]: Symbol not found: cbc_glp_prob
Referenced from: /usr/local/Cellar/cbc/2.10.7_1/lib/libCbcSolver.3.10.7.dylib
Expected in: /usr/local/Cellar/coinutils/2.11.6/lib/libCoinUtils.3.11.6.dylib
zsh: abort cbc

I also trying to test cbc with other command of python package: % oemof_installation_test
but I get following:

Solver installed with oemof:

cbc: not working
glpk: working
gurobi: not working
cplex: not working

oemof successfully installed.

and similarly the codes with calling of cbc solver are also not executable.
waiting for positive response. Thanks in advance

**Comment by p-snft** [comment]
As this is a problem with installing cbc, we cannot fix it in solph. Thus, I will close this here.

The [user forum](https://forum.openmod.org/tag/oemof) would be a better place to ask for help. In particular, probably nobody here is really proficient with MacOS. (My experience is about five years old and I could never really decide between brew and ports.) I will leave two possible solutions/ workarounds, though:
1. Use glpk instead of cbc. It seems to be working. (It might be enough for working with small models. I have the experience that cbc is faster.)
2. Install cbc using https://sysid.github.io/cbc/.

**Comment by Afraz85** [comment]
@p-snft , thanks for the information. Yes you are right I posted the same issue on coin-or  page as well.
I am using oemof libraries and solved example for my project and further contribution. But examples which call solver 'cbc' gives me error. Although cbc is installed on my MAC, but it can not find via pyomo.

**Comment by p-snft** [comment]
To use solph, you could just change the solver in the examples.

PS: It's probably a problem related to brew rather than cbc.

**Comment by Afraz85** [comment]
I have tried with sources as well with the following commands but I am unable to set the path.
wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
chmod u+x coinbrew
./coinbrew fetch Cbc@master
./coinbrew build Cbc

Now I will try with the solution you propsed in para2 above thanks.

**Comment by Afraz85** [comment]
@p-snft , I have successfully installed cbc, and passes the oemof.solph self test but still I am unable to simulate the examples with cbc.  The pyomo could not locate the solver?
<img width="1026" alt="Screenshot 2022-03-18 at 21 03 40" src="https://user-images.githubusercontent.com/58227413/159076173-b90f84aa-be7f-4311-8bdf-e9c4a16bac06.png">

**Comment by Afraz85** [comment]
@p-snft , I have successfully installed cbc, and passes the oemof.solph self test but still I am unable to simulate the examples with cbc. The pyomo could not locate the solver?
<img width="1100" alt="Screenshot 2022-03-18 at 21 15 51" src="https://user-images.githubusercontent.com/58227413/159077249-96d6b147-57f9-4279-bcb4-d2b4b772ef5c.png">

**Comment by uvchik** [comment]
I guess your IDE does no find the path of the solver. Oemof-Check was started from the console but the example from your IDE. If you start the example from the console it should work. I do not know how to add pathes to the PATH in OSx but sometime it is different for consoles and for graphical programs.

**Comment by Afraz85** [comment]
thanks Oemof/Oemof-Solph. I am able to configure cbc.
*Best Regards *
*Afraz Mehmood*

*+32 465 91 38 21*
