### ISSUE TITLE
Variable loss_rate in GenericStorage

### ISSUE THREAD

**Issue by aljubrmj** [oemof/oemof-solph#833]
If the loss_rate varies depending on the conditions at different points of time, then how can we incorporate that in GenericStorage? My understanding is that loss_rate is set apriori for all timesteps and does not change throughout the optimization process.

**Comment by p-snft** [comment]
There are three kinds of losses ([see documentation](https://oemof-solph.readthedocs.io/en/stable/reference/oemof.solph.html#oemof.solph.components.generic_storage.GenericStorageBlock))
- loss_rate,
- fixed_losses_relative, and
- fixed_losses_absolute.
All three can take time-dependent (but constant) values.

As this is more of a modelling discussion then a software issue, I'd ask you to continue in the [https://forum.openmod.org/tag/oemof](forums) if you still have questions.
