### ISSUE TITLE
Documentation: Installing a solver

### ISSUE THREAD

**Issue by FelixMau** [oemof/oemof-solph#835]
reffering to https://github.com/oemof/oemof-solph#installation

When using Pycharm: An installed solver could not be found by the the shell in Pycharm. In this case it might be helpful to use a (mini)[conda](https://docs.conda.io/en/latest/miniconda.html#miniconda) environment. A CBC solver for that purpose is available [here](https://anaconda.org/conda-forge/coincbc) 
Suggested order is: 
1. Install (mini)conda
2. Setup Conda environment in Pycharm
3. pip install oemof.solph
4. conda install -c conda-forge coincbc

**Comment by p-snft** [comment]
Thanks for the suggestion. Actually, the documentation of conda recommends to use pip after conda.

**Comment by FelixMau** [comment]
Correct, however I was installing in the recommended order in the first place but it did not work. Now with a second attempt it did work. Maybe I accidentally chose Python  3.10 on my first try.
