### ISSUE TITLE
Add option to prevent direction constraints in Link component

### ISSUE THREAD

**Issue by henhuy** [oemof/oemof-solph#837]
There has been an update in the LinkBlock component, which adds directional flow constraints.
Unfortunately, this feature breaks Link creation in oemof_tabular. 
I suggest to add an option `limit_direction` (which defaults to `True`) in Link component, by which direction constraints can be disabled.

**Comment by p-snft** [comment]
As the component is experimental anyway, I don't see any reason not to change it quickly. PR is merged, I will close this. Thanks!
