### ISSUE TITLE
latest CPLEX solver crashes om.solve(solver='cplex')

### ISSUE THREAD

**Issue by ddceruti** [oemof/oemof-solph#841]
When solving a problem with CPLEX version 22.1.0, it returns IndexError: list index out of range. I think that it is due to the pyomo version "pyomo >= 5.7.0, < 5.7.3" (see Additional comments below).

**To Reproduce**
Solve any problem with pyomo== 5.7.2 with CPLEX 22.1.0 in the default oemof environment, such as:

```
import pyomo.environ as pyo
model = pyo.ConcreteModel()
model.x = pyo.Var([1,2], domain=pyo.NonNegativeReals)
model.OBJ = pyo.Objective(expr = 2*model.x[1] + 3*model.x[2])
model.Constraint1 = pyo.Constraint(expr = 3*model.x[1] + 4*model.x[2] >= 1)
instance = model.create_instance()
opt = pyo.SolverFactory('cplex')
opt.solve(instance)
```
![oemof_bug](https://user-images.githubusercontent.com/52672045/167134574-ee4b6d94-d11b-4bce-9d10-4dd78287e18c.png)

**Expected behavior**
GUROBI solves the problem just fine.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10
 - Python version 3.8
 - latest oemof pip version installed through miniconda3
 - VS Code version 1.66

**Additional comments**
I think that this is due to the pyomo version: [https://groups.google.com/g/pyomo-forum/c/gCemf7qgrDA](https://groups.google.com/g/pyomo-forum/c/gCemf7qgrDA).

**Comment by uvchik** [comment]
Thank you @ddceruti for reporting this.

I am not sure why `Pyomo` does not return the "termination condition" but we should make sure that `solph` does not crash in that case. My plan is that solph will return `termination condition: unkown" in that case.

**Comment by uvchik** [comment]
@ddceruti , if you want to fix it quick, you could change the following lines in ...solph/_models.py (line 218ff):

```diff
- termination_condition = solver_results["Solver"][0][
-             "Termination condition"
-         ]
+ termination_condition = solver_results["Solver"][0].get(
+            "Termination condition", "unknown"
+        )
```

**Comment by ddceruti** [comment]
Thank you!

**Comment by uvchik** [comment]
Does the changes work for you.

I will keep this issue open as a reminder to catch such issues permanently.

**Comment by ddceruti** [comment]
Hi again,
sorry I just tried the quick fix now (see arrow in the screenshot). It seems that the error is thrown before the quickfix solution:

![oemof_bug_2](https://user-images.githubusercontent.com/52672045/167603462-66a504ad-ddf9-4e95-b02d-b2f745d4b1e2.png)

The issue is due to the compatilibity of pyomo ("pyomo >= 5.7.0, < 5.7.3") with the latest CPLEX one 22.1.0.  If I run a dummy problem with pyomo 6.4.0. I cannot reproduce this IndexError. For the moment I will switch to gurobi, as this solver does not have any issues with that pyomo version.

**Comment by uvchik** [comment]
Thank you for the feedback. Sorry, I misinterpreted the error message.

We are about to release the version v0.5. of solph. This version will work with the newest version of Pyomo and everything should be fine again.

**Comment by ddceruti** [comment]
Sounds great! I will test it as soon as it is published. Thank you for your time.
