### ISSUE TITLE
ModuleNotFoundError: No module named 'oemof.solph'

### ISSUE THREAD

**Issue by VincentTasara** [oemof/oemof-solph#870]
How 
can I best resolve this issue, please assist me.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_10116\3929857190.py in <module>
      3 import os
      4 import time
----> 5 import oemof.solph as solph
      6 import oemof.outputlib as outputlib
      7 import oemof.network as Node

~\anaconda3\envs\FYP\lib\site-packages\oemof\__init__.py in <module>
      1 __version__ = "0.4.5.dev0"
      2 
----> 3 from . import buses
      4 from . import components
      5 from . import constraints

~\anaconda3\envs\FYP\lib\site-packages\oemof\buses\__init__.py in <module>
     10 """
     11 
---> 12 from . import experimental
     13 from ._bus import Bus
     14 

~\anaconda3\envs\FYP\lib\site-packages\oemof\buses\experimental\__init__.py in <module>
      8 """
      9 
---> 10 from ._electrical_bus import ElectricalBus
     11 
     12 __all__ = [

~\anaconda3\envs\FYP\lib\site-packages\oemof\buses\experimental\_electrical_bus.py in <module>
     17 """
     18 
---> 19 from oemof.solph.buses._bus import Bus
     20 
     21 

ModuleNotFoundError: No module named 'oemof.solph'

**Comment by p-snft** [comment]
Sounds like you installed both packages, `oemof` and `oemof.solph`. I just added an advice to our readme, as it is a common mistake: https://github.com/oemof/oemof-solph#introduction

**Comment by VincentTasara** [comment]
Thank you!
