### ISSUE TITLE
NameError: name 'solph' is not defined

### ISSUE THREAD

**Issue by VincentTasara** [oemof/oemof-solph#872]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 opt= opti1gen(start='2018-01-01', number_of_time_steps=24*1, n_gen=2, pv_price=1250, fuel_price1=0.3)

Input In [5], in opti1gen(start, number_of_time_steps, n_gen, pv_price, fuel_price1, fuel_price2)
     15 data=data[first: last]
     17 #Initialization of the energy system
---> 18 energysystem = solph.EnergySystem(timeindex=date_time_index)
     20 logging.info('Create oemof objects')
     22 # The bus objects were assigned to variables which makes it easier to connect
     23 # components to these buses (see below).
     24 
     25 # create electricity bus

NameError: name 'solph' is not defined

**Comment by p-snft** [comment]
This seems to be related to #871. (There is more information in the other issue, so I am closing this one.)
