### ISSUE TITLE
Formulas not shoing in offline doc

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof-solph#879]
**Describe the bug**
When you build and watch the docs locally, formulas are not rendered. Instead, the LaTeX code is presented.

**To Reproduce**
1. Checkout solph
2. Build docs (`sphinx-build -b html docs dist/doc`)
3. Open freshly build docs

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4871848/201007501-1e049ab4-23a7-40aa-9b87-3b5e5d1162b2.png)

**Additional context**
The formulas are actually rendered. The problem is that they are not included correctly in the html. (Web servers might be able to handle that as the docs show correctly at readthedocs.)

**Comment by fwitte** [comment]
Can you try

‘python -m sphinx docs docs/_build’? I could after coffee as well :).

**Comment by fwitte** [comment]
Or even 

`python -m sphinx-autobuild docs docs/_build`

**Comment by p-snft** [comment]
Same problem: Source is given as `<img class="math" src="_images/math/(hash).png" alt="P_{i}"/>` but as the html file sits in "reference", the include does not work.
