### ISSUE TITLE
GenericStorage is missing `custom_attributes` attribute

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-solph#906]
In #877, all components got `custom_attributes`, apart from GenericStorage.

**Comment by p-snft** [comment]
That's because all custom attributes where also ignored before. So, if you mistyped something, nothing happened, even no attribute was added.

**Comment by jnnr** [comment]
I don't see the difference. Before making kwargs explicit, GenericStorage and e.g. Sink just passed args and kwargs to the next class in the hierarchy. Now, kwargs have been dropped and for those cases where you want to set other attributes, you pass them via custom_attributes. How is GenericStorage different to e.g. Sink?

**Comment by p-snft** [comment]
Well, `GenericStorage` did not pass it. Maybe that was not intentional, I just meant to not blame whoever did the explicit kwargs for `GenericStorage`. We can sure change that.

**Comment by uvchik** [comment]
@p-snft is right. It was possible to add an Attribute to the `Flow` class but not to Nodes as `Transformer` or `GenericStorage`. I do not know why and I doubt that this was intended.

To make it easier to add additional constraints it should be possible to attributes to components as well but as it was not possible in previous versions it is a new feature so we can add it when it is finished in any version we want. In my opinion it does not block the v0.5.0 release.

Anyhow it could be more consistent in the announcements. "Now it is possible to add `custom_ attributes` to all Flow and Components" sounds better than "Now it is possible to add `custom_ attributes` to all Flow and most Components".

But I am fine with v0.5.1. Just poke me at the matrix chat, if you need a quick review.

**Comment by p-snft** [comment]
I agree that we should be consistent. Current status is:

- `custom_attributes` exist for `Flow` and all components except ``GenericStorage`.
- `custom_attributes` add class attributes for instances of the `Flow`
- `custom_attributes` are ignored (literally nothing happens) for all components

For the flow, the keyword is (and always was) evaluated within solph.

I see two options:
1. Store the attributes is in `oemof.network`. This way, handling for Flow and Components could be done using a single implementation. We need to update network for that, having `custom_attributes` in solph is a preparation for that.
2. Implement the handling inside the solph classes.

I'd opt for the first option and accept that there will be a useless keyword for some time.

**Comment by jnnr** [comment]
Thanks for giving this some thoughts!

Regarding the options: Currently, the handling for Flow uses option 2): set the attributes in the solph class. 

I agree with you @p-snft that 1) would avoid code duplication. To be concrete, we would alter `Entity` for it to set kwargs, which will cover both Flow and all Components. Are there any reasons for disallowing this? I don't see them. oemof.network would become very liberal accepting any kwargs, solph is already strict, which is good. Feel free to proceed.

**Comment by p-snft** [comment]
Solution 1 (solph part) is implemented in  #908.
