### ISSUE TITLE
Error in Generic Invest in oemof v05

### ISSUE THREAD

**Issue by ChristophPelsLeusden** [oemof/oemof-solph#921]
**Describe the bug**
The "example_generic_invest.py" causes the following error message
"__init__() got an unexpected keyword argument 'space'"
When I comment lines 135 and 153, the example runs with oemof V05.

Remark: I was trying to update https://github.com/oemof-heat/educational_project to oemof-v05. Here I need to integrate the an additional invest flow limit.  Because I received the same error message mentioned above, I tried to run the example.

**To Reproduce**
1.  Install oemof v05 (Master)
2.  Run example_generic_invest.py
3.  See error message
4.  Comment lines 135 and 153 
5.  No error message.

I do hope that there is no error on my side.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 -   OS: Windows 10
 -   Python version: 3.8

Package                       Version
----------------------------- ---------
alabaster                     0.7.12
argh                          0.26.2
arrow                         1.2.3
astroid                       2.11.7
atomicwrites                  1.4.0
attrs                         22.1.0
autopep8                      1.6.0
Babel                         2.11.0
backcall                      0.2.0
bcrypt                        3.2.0
binaryornot                   0.4.4
black                         22.6.0
bleach                        4.1.0
blinker                       1.5
brotlipy                      0.7.0
certifi                       2022.12.7
cffi                          1.15.1
chardet                       4.0.0
charset-normalizer            2.0.4
click                         8.0.4
cloudpickle                   2.0.0
colorama                      0.4.6
comm                          0.1.2
contourpy                     1.0.7
cookiecutter                  1.7.3
cryptography                  38.0.4
cycler                        0.11.0
debugpy                       1.5.1
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.6
docutils                      0.18.1
entrypoints                   0.4
fastjsonschema                2.16.2
flake8                        4.0.1
flit_core                     3.6.0
fonttools                     4.38.0
idna                          3.4
imagesize                     1.4.1
importlib-metadata            4.11.3
importlib-resources           5.2.0
inflection                    0.5.1
intervaltree                  3.1.0
ipykernel                     6.19.2
ipython                       7.31.1
ipython-genutils              0.2.0
isort                         5.9.3
jedi                          0.18.1
jellyfish                     0.9.0
Jinja2                        3.1.2
jinja2-time                   0.2.0
jsonschema                    4.17.3
jupyter_client                7.4.9
jupyter_core                  5.2.0
keyring                       23.4.0
kiwisolver                    1.4.4
lazy-object-proxy             1.6.0
MarkupSafe                    2.1.1
matplotlib                    3.7.0
matplotlib-inline             0.1.6
mccabe                        0.7.0
mistune                       0.8.4
mypy-extensions               0.4.3
nbconvert                     5.6.1
nbformat                      5.7.0
nest-asyncio                  1.5.6
networkx                      3.0
numpy                         1.24.2
numpydoc                      1.5.0
oemof.network                 0.5.0a1
oemof.solph                   0.5.0
oemof.tools                   0.4.2
packaging                     22.0
pandas                        1.5.3
pandocfilters                 1.5.0
paramiko                      2.8.1
parso                         0.8.3
pathspec                      0.10.3
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.4.0
pip                           22.3.1
pkgutil_resolve_name          1.3.10
platformdirs                  2.5.2
pluggy                        1.0.0
ply                           3.11
poyo                          0.5.0
prompt-toolkit                3.0.36
psutil                        5.9.0
ptyprocess                    0.7.0
pycodestyle                   2.8.0
pycparser                     2.21
pydocstyle                    6.3.0
pyflakes                      2.4.0
Pygments                      2.11.2
pylint                        2.14.5
pyls-spyder                   0.4.0
PyNaCl                        1.5.0
Pyomo                         6.5.0
pyOpenSSL                     22.0.0
pyparsing                     3.0.9
PyQt5                         5.15.7
PyQt5-sip                     12.11.0
PyQtWebEngine                 5.15.4
pyrsistent                    0.18.0
PySocks                       1.7.1
python-dateutil               2.8.2
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.5.0
python-slugify                5.0.2
pytz                          2022.7.1
pywin32                       305.1
pywin32-ctypes                0.2.0
PyYAML                        6.0
pyzmq                         23.2.0
QDarkStyle                    3.0.2
qstylizer                     0.2.2
QtAwesome                     1.2.2
qtconsole                     5.3.2
QtPy                          2.2.0
requests                      2.28.1
rope                          0.22.0
Rtree                         1.0.1
setuptools                    65.6.3
sip                           6.6.2
six                           1.16.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
Sphinx                        5.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.3.3
spyder-kernels                2.3.3
testpath                      0.6.0
text-unidecode                1.3
textdistance                  4.2.1
three-merge                   0.1.1
tinycss2                      1.2.1
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.1
tornado                       6.2
traitlets                     5.7.1
typing_extensions             4.4.0
ujson                         5.4.0
Unidecode                     1.2.0
urllib3                       1.26.14
watchdog                      1.0.2
wcwidth                       0.2.5
webencodings                  0.5.1
whatthepatch                  1.0.2
wheel                         0.37.1
win-inet-pton                 1.1.0
wincertstore                  0.2
wrapt                         1.14.1
yapf                          0.31.0
zipp                          3.11.0

**Comment by p-snft** [comment]
Thanks for pointing this out. Before v0.5, unknown keywords were sometimes used as custom attributes. A drawback was, that unknown arguments (possibly typos) silently ignored. Now, there is the argument `custom_attributes` to explicitly set custom attributes. For some reason, this was not adjusted in the example. I fixed it in dev: https://github.com/oemof/oemof-solph/blob/dev/examples/generic_invest_limit/example_generic_invest.py

PS: Unfortunately, your workaround removes the custom attribute that is needed for the constraint to be meaningful.

**Comment by ChristophPelsLeusden** [comment]
Thanks for the solution. This works.
For clarification: I did not mean to remove the custom attribute permanently. I just wanted to check where the error message comes from.
