### ISSUE TITLE
Examples are untested

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof-solph#922]
For some reason, I believed examples were tested automatically, but #921 proves, they are not. We should really fix that, In particular, because better consistency was one reason why we moved the examples into the repository.

**Comment by tobirohrer** [comment]
Hey, 

I would like to help with this task :)

As far as I see, there is a `check_examples.py` in `/examples`, but I don't fully understand its functionality... It seems to check jupyter notebooks, but I cannot find any in the `/examples` folder.

What are your requirements for the examples tests? Are "smoke tests" enough to check if they run without errors?

I don't know all the example scripts, but we must keep in mind that a test of each example script also increases the runtime of the testsuite...

**Comment by p-snft** [comment]
Hi Tobi,

In my opinion, smoke tests are good, as we have unit tests for the individual modules. In fact, the check_examples.py is fine, but might be documented better. (It can run notebooks which is useful to not be restrictive when allowing examples.)

Some minimal integration into the workflows would be good. I don't think, they should all be tested for every commit. There might be something like a tox target that is only run when merging into master (and offline).

**Comment by p-snft** [comment]
I just added "examples/check_examples.py" to the release documentation in the Wiki. This should be good enough for now.
