### ISSUE TITLE
oemof_installation_test not working after update to 0.5

### ISSUE THREAD

**Issue by david-huck** [oemof/oemof-solph#930]
**Describe the bug**
Recently, I updated to the newer version of oemof, and noticed, that the `oemof_installation_test` doesn't work anymore, but instead throws an error.

**Steps to  Reproduce**
1.  Create and activate new environment 
    * `conda create -n oemof-test python=3.9 pip`
    * `conda activate oemof-test`
3.  install `oemof.solph`: `pip install oemof.solph==0.5.0`
4.  run `oemof_installation_test`
5.  See error
```python
Traceback (most recent call last):
  File "...\.conda\envs\oemof-test\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "...\.conda\envs\oemof-test\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "...\.conda\envs\oemof-test\Scripts\oemof_installation_test.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'oemof.solph.console_scripts'
```

This error disappears when downgrading to the older `oemof.solph==0.4`.

**Expected behavior**
Expected to see the good old message of the installation test:

```
*********
Solver installed with oemof:
glpk: working
cplex: not working
cbc: working
gurobi: not working
*********
oemof.solph successfully installed.
```

**Desktop (please complete the following information):**
 -   OS: Ubuntu20, Windows11
 -   Python 3.8 and 3.9

**Comment by p-snft** [comment]
Hi @david-huck, thanks for bringing this up. We missed to properly bundle that script. It was already fixed in dev, but I now decided to create a development release including the fix: https://pypi.org/project/oemof.solph/0.5.1.dev0/
