### ISSUE TITLE
Readthedocs build not recent

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof-solph#939]
The build of the docs at readthedoc fails. There are different errors ([see full log](https://readthedocs.org/api/v2/build/20606901.txt)), e.g.:

> ! LaTeX Error: Unknown graphics extension: .svg.

or

> l.10197 ...in \textrm{NONCONVEX_FLOWS}.\end{split}
>                                                   
> ! Missing $ inserted.

So, in total

> (That makes 100 errors; please try again.)
> !  ==> Fatal error occurred, no output PDF file produced!
> Transcript written on oemof-solph.log.
> Latexmk: Index file 'oemof-solph.idx' was written
> Failure to make 'oemof-solph.pdf'
> Latexmk: Errors, in force_mode: so I tried finishing targets
> Collected error summary (may duplicate other messages):
>  pdflatex: Command for 'pdflatex' gave return code 256

**Comment by fwitte** [comment]
If I remember correctly, it was related to this: https://github.com/oemof/tespy/commit/d08a784f2b1fa30eca378bd6f083daf79d8c305c

**Comment by fwitte** [comment]
Ah that guess was too fast.

Still, I remember there was a similar issue on TESPy: something was changed at sphinx or rtd to make the build fail on latex errors (instead of ignoring them, which was the case before). Therefore I disabled everything but html build on TESPy…
