### ISSUE TITLE
Handling period-specific parameters in multi-period-investment

### ISSUE THREAD

**Issue by nailend** [oemof/oemof-solph#959]
Dear all,

in our current project, we want to make use of period-specific parameters in a multi-period-investment. Currently, the only way to do this is passing an iterable to this parameter with values for every timestep. As we are using `omeof.tabular`, we could integrate a preprocessing to generate timeseries there, but we would find a `oemof.solph` solution more charming from user perspective. 

We would like to hear your opinion about this and collect possible challenges/restrictions. The idea is to adapt `_plumbing.sequence`, that if a tuple or maybe dict is passed, it returns period specific values. This would change the functionality of the function fundamentally, as the length of the list would need to be known. Further, the number of timesteps per periods need to be passed. This should be optional, so that the original way is preserved.

* Do you have any idea. how to handle this?
* What's the best way to pass periods information?
* Could there be any problems with detecting tuple or dict from csv? (This needs to be handled in `oemof.tabular` `read_from_datapackage`)

@jokochems, @p-snft, do you have any thoughts on this?

We are looking forward to your ideas and thank you for your help.

**Comment by p-snft** [comment]
If it's okay, I'd like to finish [v0.5.1](https://github.com/oemof/oemof-solph/milestone/27) before concentrating on this. (We can have v0.5.2.dev0 directly afterwards, if you like.)

**Comment by nailend** [comment]
We decided to solve this in oemof.tabular as this approach comes with more difficulties then expected...
