### ISSUE TITLE
Oemof_installation_test fails to find module (ModuleNotFoundError

### ISSUE THREAD

**Issue by Siebenfurcht** [oemof/oemof-solph#972]
Hello,
this is my first issue, however I am stuck here. I am running Pycharm on Ubuntu and want to work with Oemof. When I follow the installation guide (I use a venv in Pycharm) I can successfully install oemof.solph. When I want to run `oemof_installation_test` I get the following error:

`(venv) user@Laptop:~/PycharmProjects$ oemof_installation_test
Traceback (most recent call last):
  File "/home/user/PycharmProjects/venv/bin/oemof_installation_test", line 5, in <module>
    from oemof.solph.console_scripts import check_oemof_installation
ModuleNotFoundError: No module named 'oemof.solph.console_scripts'
`

However, when I go into the directory and change the name of `_console_scripts.py` to `console_scripts.py`, I can successfully run  `oemof_installation_test`.

`(venv) user@Laptop:~/PycharmProjects$ oemof_installation_test
^[[3~/home/userPycharmProjects/venv/lib/python3.10/site-packages/oemof/solph/_energy_system.py:87: FutureWarning: The default behaviour will change in future versions.
At the moment the last interval of an equidistant time index is added implicitly by default. Set 'infer_last_interval' explicitly 'True' or 'False' to avoid this warning. In future versions 'False' will be the defaultbehaviour
  warnings.warn(msg, FutureWarning)

*****************************
Solver installed with oemof:

cbc: working
glpk: not working
gurobi: not working
cplex: not working

*****************************
oemof successfully installed.
*****************************
`
![image](https://github.com/oemof/oemof-solph/assets/22994478/1893e10d-50d2-49ec-b996-573da918371b)

Can someone help with this issue?

**Comment by p-snft** [comment]
Hi @Siebenfurcht,

thanks for reporting this issue. Actually, we forgot to bundle it in the pip package (v0.5.0) and somehow it was not recognised prior release as nobody tested it. It is fixed in the upcoming release (see [v0.5.1 changelog](https://github.com/oemof/oemof-solph/blob/v0.5.1rc1/docs/whatsnew/v0-5-1.rst#bug-fixes)), which is scheduled for this week. You can install the pre-release version using `pip install oemof.solph==0.5.1rc1`.

**Comment by Siebenfurcht** [comment]
Hello Patrik,
I have followed your instructions and I was able to solve the issue. Thanks a lot.
