### ISSUE TITLE
Get Basic Example working in Oemof.Solph

### ISSUE THREAD

**Issue by Siebenfurcht** [oemof/oemof-solph#976]
Hello,

I am fairly new to Oemof, thus I hope that my questions are not to trivial. I have been trying to run Oemof.Solph 0.5.1 and setting up the [basic example](https://github.com/oemof/oemof-solph/tree/dev/examples/basic_example) for learning purposes. I have identified the need to change the code e.g. from
`energysystem.add(solph.Sink...)` to `energysystem.add(solph.components.Sink...)`
However, when I run the modified script, I get the following result:

```
/home/user/PycharmProjects/Oemof/venv/bin/python /home/user/PycharmProjects/Oemof/basic_example.py
13:24:11-INFO-Path for logging: /home/user/.oemof/log_files/oemof_example.log
13:24:11-INFO-Initialize the energy system
13:24:11-INFO-Create oemof objects
13:24:11-INFO-Optimise the energy system`

Traceback (most recent call last):
  File "/home/user/PycharmProjects/Oemof/basic_example.py", line 183, in <module>
    model = solph.Model(energysystem)
  File "/home/user/PycharmProjects/Oemof/venv/lib/python3.10/site-packages/oemof/solph/_models.py", line 377, in __init__
    super().__init__(energysystem, **kwargs)
  File "/home/user/PycharmProjects/Oemof/venv/lib/python3.10/site-packages/oemof/solph/_models.py", line 113, in __init__
    raise LoggingError(msg)

oemof.solph._models.LoggingError: The root logger level is 'DEBUG'.
Due to a communication problem between solph and the pyomo package,
using the DEBUG level will slow down the modelling process by the factor ~100.
If you need the debug-logging you can initialise the Model with 'debug=True`
You should only do this for small models. To avoid the slow-down use the logger
function of oemof.tools (read docstring) or change the level of the root logger:

import logging'
logging.getLogger().setLevel(logging.INFO)
Process finished with exit code 1
```

I am a little bit lost here and would appreciate some guidance or advice.

Regards

Siebenfurcht

**Comment by p-snft** [comment]
Hi @Siebenfurcht,

honestly, I do not really get this. In the example you linked, it already says `energysystem.add(solph.components.Sink...)`, so there is no need to adjust that. Could you tell what you did to install oemof.solph? Also, the output of `pip list` would be helpful.

**Comment by Siebenfurcht** [comment]
Hi @p-snft,

thanks for your reply. I just made a mistake. Reinstalling everything has helped me to resolve the issue, the Basic Example is now running well.

Regards
