### ISSUE TITLE
Outdated docs for use of multi-periods

### ISSUE THREAD

**Issue by henhuy** [oemof/oemof-solph#978]
In the multi-period section in the docs it's stated that you can parametrize the periods as `dict`:
https://github.com/oemof/oemof-solph/blob/f02297ea7db0134bfff12c3ff6c7c909ca4405ed/docs/usage.rst#L1027-L1035

This seems to be outdated (I think a list should be used instead), as I get error `AttributeError: 'int' object has no attribute 'min'` in line https://github.com/oemof/oemof-solph/blob/f02297ea7db0134bfff12c3ff6c7c909ca4405ed/src/oemof/solph/_energy_system.py#L192

**Comment by jokochems** [comment]
Thanks, @henhuy. I'll provide a fix shortly. If you have time, feel free to already do so.
