### ISSUE TITLE
Periodic fixed costs in multi-period investment

### ISSUE THREAD

**Issue by nailend** [oemof/oemof-solph#983]
I am currently looking in periodically changing fixed-costs in a multi-period invest optimization (with non yearly-invest periods, e.g. 2021, 2023,...).
For this, a want to pass a list of values for each period to `fixed_costs`.

This would need some minor changes in the investment flow block:
- Change the index `pp` to `p` of `m.flows[i, o].investment.fixed_costs` in [invest](https://github.com/oemof/oemof-solph/blob/f02297ea7db0134bfff12c3ff6c7c909ca4405ed/src/oemof/solph/flows/_investment_flow_block.py#L922C50-L922C50)
- Change the index `pp` to `0` of `m.flows[i, o].investment.fixed_costs` in [existing invest](https://github.com/oemof/oemof-solph/blob/f02297ea7db0134bfff12c3ff6c7c909ca4405ed/src/oemof/solph/flows/_investment_flow_block.py#L936C61-L936C61) as the fixed costs are equal to the ones of the first period

**Drawbacks:**

- fixed costs values are the same for the whole lifetime of the component, even though the time between periods with different values are shorter
- ...

Alternatively, the list could contain values for each year  (not only the invest-periods) but this would not cohere with input of the length of other parameters. Further, the list would have to be appended by a number of values with the length of the lifetime to not raise an index error for an investment in the last period.

@jokochems do you think these changes are possible without changing the current behavior? I would assume so, as fixed_costs are currently passed as default value for `sequence()`
@henhuy Are the drawbacks acceptable?

**Comment by henhuy** [comment]
I think as fixed_costs are implemented in more detail (yearly based), we should not make them less detailed, by limiting them to period based values. Instead, if such behavior should be implemented, yearly-based values should be calculated upfront from periodic values... 

> Further, the list would have to be appended by a number of values with the length of the lifetime to not raise an index error for an investment in the last period.

This is indeed unfortunate, as user would have to know this - maybe we could check if fixed_costs expanding periodic_years length exist and otherwise use last years value for remaining years?

**Comment by jokochems** [comment]
> think as fixed_costs are implemented in more detail (yearly based), we should not make them less detailed, by limiting them to period based values. Instead, if such behavior should be implemented, yearly-based values should be calculated upfront from periodic values...
> 
> > Further, the list would have to be appended by a number of values with the length of the lifetime to not raise an index error for an investment in the last period.
> 
> This is indeed unfortunate, as user would have to know this - maybe we could check if fixed_costs expanding periodic_years length exist and otherwise use last years value for remaining years?

I fully agree to everything you stated. You are right about the problems with the lifetime. I guess, this will be resolved once I'm finalized with #982.
