### ISSUE TITLE
FutureWarnings from oemof.network are showing

### ISSUE THREAD

**Issue by jokochems** [oemof/oemof-solph#998]
When running a model using a current installation from a feature branch that is up to date with the dev branch, I get a lot of `FutureWarning`s from `oemof.network` saying that `oemof.network.Component` is deprecated and `oemof.network.Node` should be used instead.

I had a look into the code basis and saw that components such as a `Source` or a `Sink` are still derived from `oemof.network.Component`, not `oemof.network.Node` in the `oemof.network` version that is installed alongside with the dev version of solph.

I assume this is just a temporary issue due to ongoing development in `oemof.network` that will be fixed by updated dependencies soon. Am I right, @p-snft, and this is already on your list?

Here are the package versions
oemof.network: 0.5.0a5
oemof.solph: 0.5.2.dev1

**Comment by jokochems** [comment]
A small addition: The same holds for `oemof.network.Bus` as well which should be replaced by `oemof.network.Node`.

**Comment by p-snft** [comment]
This is fixed in #990, which is is waiting for a review from your sine. (That PR also fixes a lot of other deprecation warnings.)

**Comment by jokochems** [comment]
Closed by #990
