### ISSUE TITLE
How to set 2 Sink (not fixed) whose result values are proportional？

### ISSUE THREAD

**Issue by Steven-HDQ** [oemof/oemof-solph#999]
Hello, my dear friends.  I am going to create an energy system.  There are two Sinks which are not fixed and they are in different topological levels , and I need their result values after solver to be proportional (at each timestamp).  Is it possible?  How can I set them? In another method, I find that one Sink can have multi inputs (though not recommended), can I set the two input flows to make their result values to be proportional? Thanks a lot!

**Comment by p-snft** [comment]
Hi @Steven-HDQ,

There is the [constraint equate_flows](https://oemof-solph.readthedocs.io/en/latest/reference/oemof.solph.constraints.html#oemof.solph.constraints.equate_flows), which directly implements what you asked for. Alternatively, you could also deviate from the physical topology and create a logical topology. This way, you can just use a `Converter`.

PS: Questions are best asked in the openmod forum: https://forum.openmod.org/tag/oemof-solph

**Comment by Steven-HDQ** [comment]
> There is the [constraint equate_flows](https://oemof-solph.readthedocs.io/en/latest/reference/oemof.solph.constraints.html#oemof.solph.constraints.equate_flows), which directly implements what you asked for. Alternatively, you could also deviate from the physical topology and create a logical topology. This way, you can just use a `Converter`.

@p-snft Thank you for your advice！
Your answer helped me know more and deeper about the constraint part of oemof.solph. The Converter works perfectly for me!
Thanks again for your kindly and great job!
